### ISSUE TITLE
Get the user_id from OAuthTokens

### ISSUE THREAD

**Issue by razvanbretoiu** [BingAds/BingAds-Python-SDK#100]
Hi,

I need the [_UriOAuthService.get_access_token](https://github.com/BingAds/BingAds-Python-SDK/blob/master/bingads/authorization.py#L613) method to return an `OAuthTokens` with the `user_id` in it.
 
Bing service returns the `user_id`, but the `OAuthTokens` class doesn't have an `user_id` attribute.

Can you add the `user_id` to the `OAuthTokens` class ? 
Or is another way were I can get the `user_id` ?

**Comment by dariusmb** [comment]
I created a PR for this problem

**Comment by eric-urban** [comment]
@razvanbretoiu @dariusmb will you please clarify the requirement? The user_id in the auth request is NOT a Bing Ads system user ID. If you need the [user ID](https://docs.microsoft.com/en-us/bingads/customer-management-service/user?view=bingads-12#id) for a Bing Ads User, you can call [GetUser](https://docs.microsoft.com/en-us/bingads/customer-management-service/getuser?view=bingads-12) and set the UserId to nil/empty. If you need the Microsoft Account (MSA) user_id please clarify the use case. Thanks.

@qitia FYI

**Comment by razvanbretoiu** [comment]
@eric-urban we need the `Microsoft Account` (MSA) thats why I can't use `GetUser`.

**Comment by eric-urban** [comment]
@razvanbretoiu @dariusmb @qitia for flexibility how about let's return the full response as JSON from the token request. Clients can parse the values they care about, whether returned today or added in the future. My concern about promoting "user_id" in OAuth tokens is that someone might confuse it with the Bing Ads User ID. I haven't heard of anyone needing the MSA user_id until now.

**Comment by qitia** [comment]
as @eric-urban suggested, we return the full response as JSON. This is released with version 12.0.1.
