### ISSUE TITLE
How to get TrackingId from service result?

### ISSUE THREAD

**Issue by DrPyser** [BingAds/BingAds-Python-SDK#106]
The bing docs specify that service responses contain a `TrackingId` header. I'd like to get access to that tracking id, but it's unclear how to get it from the result of a service operation call. 

Thanks.

**Comment by qitia** [comment]
After you call method MethodA, you could try below.
headers = service_client.hp.get_headers(service_client.soap_client.service.MethodA)
tracking_id = headers['TrackingId'] if 'TrackingId' in headers else None

I know this is not straightforward, I am trying to optimize it now - hope new method could be available with version 12.0.3 in couple of days.

**Comment by DrPyser** [comment]
Ok, cool. 

If I could suggest, it would make most sense to make headers available directly from the result, as an additional "headers" attribute for example. 

Thanks for the answer!

**Comment by qitia** [comment]
you are right @DrPyser, an object wrapping the header and body will be more extendable,  however we do not want introduce big breaking change (for e.g. change the response type) as for now. Let's just add a new method to ServiceClient as said above, and see if there is chance to do more refactor in the future.

**Comment by qitia** [comment]
@DrPyser Version 12.0.3 released 10th Jan. service_client.get_response_header() is available now.

**Comment by DrPyser** [comment]
Thanks, I'll look into that.
