### ISSUE TITLE
Why is BulkFileReader so slow?

### ISSUE THREAD

**Issue by turing4ever** [BingAds/BingAds-Python-SDK#109]
@qitia 
With a few thousands of keywords in the Bulkfile, it takes quite a while to read the csv file and parse them into BulkKeyword entities. It seems it's pretty computation bound in the parsing phase, re-constructing the BulkKeyword objects one bye one. CPU 99% most of the time.
I had to run multiple processes in python to parse files in chunks to speed up the process. 
Is there anyway to optimize in BulkFileReader? Thanks!

Just FYI: I am using python sdk, the latest version. The size of my files range from 10K to 1M rows.

**Comment by qitia** [comment]
Thanks for reporting this issue and sorry for late respond. Actually this is the first time I got such feedback. May I have more context about the use case? As you said the bulk operation read the rows into iteration of entities, and you then work on the iteration. Are you just parse the rows into memory or you do make some modify/calc during the parsing? Thanks for any info.

**Comment by turing4ever** [comment]
**Context** 
Restructuring accounts with millions of keywords and AdGroups. Simple question is asked: how many keywords in the account have assigned CPC and how many of them are inheriting CPC from AdGroup. 
In total, there are 100+ accounts, 50+ of them have 1~2M keywords. 

**My Approach**
Download Keywords, AdGroups in separate BulkFiles. (This step is fast, given the file size) 
_After all files are downloaded, my program will parse each BulkFile._ (This step is taking forever.)
Construct dictionaries for AdGroups and look up keywords against AdGroup dictionaries.  (Mostly my own code)

**Problem with SDK**
It's taking forever for `BulkFileReader` to parse the download CSV file and return BulkKeyword and BulkAdGroup entities. It seems the SDK `yield` entities, not returning a giant list. So the bottleneck is inside the parsing parts of `BulkFileReader`. Maybe constructing entities dynamically one by one triggers garbage collection in python or the process involves dynamic memory allocation too many times? The CPU is constantly at 99%-100% usage. 

You would think that parsing a CSV file should be quick even at GB size. I think there's something to do inside BulkFileReader to speed it up. But I don't have time to take a deep dive.

**Comment by qitia** [comment]
@turing4ever do you still see this perf issue? we never heard this kind of escalation from other devs and I did not repro from my test env. There has been some new versions during the past months, could you please try the latest version and let us know the result?

I will close it as for now and please reopen it in case you are still facing the same issue.
