### ISSUE TITLE
Error: KeyError: 'error_description'

### ISSUE THREAD

**Issue by iamdoron** [BingAds/BingAds-Python-SDK#11]
I got OAuthTokenRequestException, but it was not raised correctly (due to KeyError: 'error_description'), so I don't know what's the issue (not able to reproduce it)

the traceback:
```
File "/usr/local/lib/python2.7/dist-packages/bingads/authorization.py", line 405, in request_oauth_tokens_by_refresh_token
      refresh_token=refresh_token,
File "/usr/local/lib/python2.7/dist-packages/bingads/authorization.py", line 585, in get_access_token
      raise OAuthTokenRequestException(error_json['error'], error_json['error_description'])
```

**Comment by imfu** [comment]
@iamdoron sorry reply you so late. I have tried to trigger an OAuthTokenRequestException, but not reproduced, I suppose the error response you got did not contain an error_description so it failed to raise the exception.
Does this issue still exist on your side? if so, could you please share the error response it returned?
