### ISSUE TITLE
v12.0.4 pip install fails

### ISSUE THREAD

**Issue by animenon** [BingAds/BingAds-Python-SDK#114]
When I run  `pip install bingads` now, it fails with:
```
Collecting bingads
  Downloading https://files.pythonhosted.org/packages/2d/35/1e8ae640061deaef5d830d57a24cd74cc83476b501c4e99cebd187e5940d/bingads-12.0.4.zip (234kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-FftbgX/bingads/setup.py", line 10, in <module>
        with open('HISTORY.rst', 'r') as f:
    IOError: [Errno 2] No such file or directory: 'HISTORY.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-FftbgX/bingads/
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by akrymskiy** [comment]
Same here! I ended up downloading the source as Zip from here, unzipping and running `python setup.py install` inside the folder. Something must have gone missing during the publishing to the repository...

**Comment by litan1106** [comment]
Same here. 

Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-d_ym0i7c/bingads/setup.py", line 10, in <module>
        with open('HISTORY.rst', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'

**Comment by elrazia** [comment]
Bump. I installed the previous version on my machine as a temporary fix:
`pip install bingads==12.0.3.1`

**Comment by qingjuntian** [comment]
I've send a new 12.0.4 package to pypi. The root cause of the issue is encoding of file manifest.in, it is somehow changed to utf-bom, and setup tool failed to parse it and pack necessary to final package.

Please download Version 12.0.4 from [pypi here](https://pypi.org/project/bingads/).
