### ISSUE TITLE
Error in the code

### ISSUE THREAD

**Issue by amitlimbaskar** [BingAds/BingAds-Python-SDK#121]
I get following error when I run Auth_helper.py

raise Exception("The OAuth response state does not match the client request state.")
        ^
IndentationError: expected an indented block

**Comment by eric-urban** [comment]
@amitlimbaskar auth_helper.py is a helper file that you should include when running the examples e.g., [search_user_accounts.py](https://github.com/BingAds/BingAds-Python-SDK/blob/master/examples/v13/search_user_accounts.py). It isn't designed to be run independently. We can add comments to clarify. I hope this helps!

**Comment by nandinilimbaskar** [comment]
Hi , how to modify auth_helper to get the data for all accounts? Currently I'm receiving the data only for 2 accounts out of 27. There is account id array but not sure how to modify to accommodate all the accounts. Thanks
