### ISSUE TITLE
Type Not Found: BudgetSummaryReportTime

### ISSUE THREAD

**Issue by cscalisi** [BingAds/BingAds-Python-SDK#122]
Hello team,

I believe that the code sample for downloading reports is broken: for Budget Summary reports, we need to define a special time dimension by calling the reporting service with type "BudgetSummaryReportTime", which cannot be found. It's [this line](https://github.com/BingAds/BingAds-Python-SDK/blob/master/examples/v13/report_requests.py#L223). 
Let me know if you need more info and thanks for the help in advance.

Cheers,
Carlo

**Comment by eric-urban** [comment]
@cscalisi thanks for reporting this issue. Starting in version 13 the budget summary report uses ReportTime, like other report types. The sample has been updated.

**Comment by cscalisi** [comment]
Thanks for the very prompt answer Eric!
