### ISSUE TITLE
How to use custom dates for report

### ISSUE THREAD

**Issue by amitlimbaskar** [BingAds/BingAds-Python-SDK#130]
How to modify  ReportTime object to run the report for custom dates? I tried following code
       time=reporting_service.factory.create('ReportTime')
       # You can either use a custom date range or predefined time.
       time.CustomDateRangeStart.Day=25
       time.CustomDateRangeStart.Month=7
       time.CustomDateRangeStart.Year=2019
       time.CustomDateRangeEnd.Day=31
       time.CustomDateRangeEnd.Month=7
       time.CustomDateRangeEnd.Year=2019

It gived me IndentationError: unexpected indent for  time.CustomDateRangeStart.Day=25

**Comment by eric-urban** [comment]
@amitlimbaskar the following snippet was proposed in the [MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/093959a8-9cfb-40e0-b988-0e82e76e990a/requesting-daily-campaign-spend-information-using-python?forum=BingAds):

```python
start_date=reporting_service.factory.create('Date')
start_date.Day=4
start_date.Month=6
start_date.Year=2019
time.CustomDateRangeStart=start_date

end_date=reporting_service.factory.create('Date')
end_date.Day=5
end_date.Month=6
end_date.Year=2019
time.CustomDateRangeEnd=end_date
```

Please let me know if you have any follow up questions.

**Comment by nandinilimbaskar** [comment]
Thanks Eric-urban
