### ISSUE TITLE
issue with bing ads version upgrade 

### ISSUE THREAD

**Issue by VishaldasM** [BingAds/BingAds-Python-SDK#132]
Hi Team,
this is regarding bing api upgrade from 12 to 13 version as published in this web page (https://docs.microsoft.com/en-us/advertising/guides/migration-guide?view=bingads-13#reporting)we are running on 11.12.4 at present. we tried to upgrade to the latest version and we are getting below error. (we are using python 2.7)(bingenv)skumar@east1-prod-dwhadmin-1:~$ pip install -U bingads
Collecting bingads
Using cached https://files.pythonhosted.org/packages/7b/e5/c09900391ca26baf290151e63c092535be96d79ab83ad3cbc5797fb89fd2/bingads-12.13.6.zip
Complete output from command python setup.py egg_info:
error in bingads setup command: ‘install_requires’ must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in enum34;python_version<“3.4” at ;python_version<“3.4" ----------------------------------------
Command “python setup.py egg_info” failed with error code 1 in /tmp/pip-build-NMxDFY/bingadswe are able to upgrade till 12.0.1 but not to any higher version than that.

Could someone look into it if we are missing anything?
the version we are using will expire very soon. Appreciate your help in it ASAP.

**Comment by eric-urban** [comment]
@VishaldasM a similar issue was resolved as noted [here](https://github.com/sdispater/pendulum/issues/187). I hope this helps!
