### ISSUE TITLE
Grant issues for version13 

### ISSUE THREAD

**Issue by VishaldasM** [BingAds/BingAds-Python-SDK#133]
Hi Team,

we upgraded bing version to 13 and tried to launch our jobs. we get below error. do we have different access levels for 13 version compared to previous versions ? (doesn't make much sense but this is what we are observing)
we are able to execute same bing jobs on degraded version even today with the same credentials but getting access issues on 13 version.

Below is the exact error for reference:

/home/hkoppuravuri/virtual/bing_v/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:380: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning,
/home/hkoppuravuri/virtual/bing_v/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning,
error_code: invalid_grant, error_description: AADSTS70000: The request was denied because one or more scopes requested are unauthorized or expired. The user must first sign in and grant the client application access to the requested scope.
Trace ID: 187438c4-f3ed-4e94-8b00-158288a31a00
Correlation ID: 2db347ca-39c4-4c91-98c1-d0117e66b071
Timestamp: 2019-10-29 05:59:22Z

Can you please help us on this..

**Comment by eric-urban** [comment]
@VishaldasM you might need new access and refresh tokens via the user consent flow. please note as of version [12.13.2](https://github.com/BingAds/BingAds-Python-SDK/releases/tag/v12.13.2): The default OAuth endpoint is updated from Live Connect endpoint to the Microsoft Identity endpoint for developers. The Microsoft Identity endpoint supports both Microsoft Account (MSA) personal credentials and Azure Active Directory (AAD) work credentials. For more information, see [Upgrade to the Microsoft identity platform endpoint FAQ](https://docs.microsoft.com/en-us/advertising/guides/authentication-oauth#upgrade-identity-platform-faq).

**Comment by thja** [comment]
@eric-urban Probably not related with the above but another grant issue we face with work/education accounts (MS accounts work fine)

```
AADSTS650052: The app needs access to a service (\"https://ads.microsoft.com\") that your organization \"6ab5da21-0423-4825-a795-bc53497e3d52\" has not subscribed to or enabled. Contact your IT Admin to review the configuration of your service subscriptions.
Trace ID: 8faa7374-db54-4a1c-8890-c79c00d93b00
Correlation ID: 48425521-1075-4d9a-9b4a-ab5f944aad1a
Timestamp: 2019-11-04 09:02:12Z&error_uri=https://login.microsoftonline.com/error?code=650052&state=eyJ0b2tlbiI6ICJkNWU3NmFjYWVkY2I0ZThiOWVhNWQ2ODUzY2FlYzg1MiIsICJob3N0IjogImh0dHBzOi8vc2NvdXQyNGRlLmRhdGF0YXAuYWR2ZXJpdHkuY29tL29hdXRoMi9jYWxsYmFjay8ifQ==
```

I'm not sure if this error message actually applies to Microsoft Ads. However I couldn't find a way to enable the mentioned service. All I found was [this app](https://azuremarketplace.microsoft.com/en/marketplace/apps/aad.bingads?tab=Overview) linking to the [password based SSO section](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/what-is-single-sign-on#password-based-sso) but I wasn't able to locate an app 'Microsoft Ads' in the Azure Portal as described [here](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/configure-password-single-sign-on-non-gallery-applications#open-the-app-and-select-password-single-sign-on).

**Comment by eric-urban** [comment]
@thja this is likely not an issue with app registration. Is your user's customer (or test customer) enabled for the work/school account [beta](https://microsoft.qualtrics.com/jfe/form/SV_6nTHpWdjStcD3Zr)? This feature is not yet generally available for all customers.

**Comment by thja** [comment]
@eric-urban I didn't know of this beta program, thanks a lot.

**Comment by thja** [comment]
@eric-urban it seems these customers are already part of the beta and using their work accounts. However login with our app doesn't work as outlined above.

The MS Ads Support sent these links to the customers, I don't see what else we could do on our end:
https://help.ads.microsoft.com/#apex/3/en/60043/-1
https://docs.microsoft.com/en-us/advertising/guides/authentication-oauth-identity-platform?view=bingads-13 -

As our Organization ID `6ab5da21-0423-4825-a795-bc53497e3d52` in mentioned in the error message, is it possible that we have to subscribe to this beta with our organization as well (or have to be white-listed, etc.) even though it's not about _our_ ad accounts?

**Comment by eric-urban** [comment]
@thja just to double check the [app registration](https://docs.microsoft.com/en-us/advertising/guides/authentication-oauth-identity-platform?view=bingads-13#registerapplication), in the Supported account types section, did you select **Accounts in any organizational directory and personal Microsoft accounts**? Otherwise I suggest that you [contact support](https://about.ads.microsoft.com/en-us/microsoft-advertising-support) with your app client ID and at least one or two examples of your customers' email logins + account numbers.

**Comment by thja** [comment]
@eric-urban yes, in the manifest file it's set as `"signInAudience":"AzureADandPersonalMicrosoftAccount"` which should be the. We'll contact the support.

**Comment by qitia** [comment]
@thja is the issue resolved? Should we close this issue now?

**Comment by thja** [comment]
@qitia from my perspective we can close it. As suggested we've contacted the support and this doesn't seem to be related with this SDK.
