### ISSUE TITLE
Passing in client_secret ?

### ISSUE THREAD

**Issue by ibrierley** [BingAds/BingAds-Python-SDK#134]
Hi, I'm just trying to get bingads api working. 

One oddity I can't follow, is that I can't figure out how to pass in client_secret from my script.

I can hack it directly, by adding the line 

self._client_secret = 'blahblah' inside class OAuthWithAuthorizationCode(OAuthAuthorization):
__init__

And then it works, but naturally I assume there's a better way ?

If it makes any difference, I've had to go down the route of manual authentication, as I'm running this on a Linux server, which tries to use elinks with no javascript support, so as a one off I've had to authenticate by copy/pasting from browser.

Thanks!

**Comment by eric-urban** [comment]
@ibrierley please use OAuthWebAuthCodeGrant if you have a client secret. Please see [Using OAuth](https://review.docs.microsoft.com/en-us/advertising/guides/sdk-authentication?view=bingads-13&branch=urban-updates-dev#oauth) for more details.

**Comment by ibrierley** [comment]
Ok, I think thats got me out of the hack :)....

So rather than using 

  authentication=OAuthDesktopMobileAuthCodeGrant( ... 

I'm using

```
    authentication=OAuthWebAuthCodeGrant(
        client_id=CLIENT_ID,
        client_secret=CLIENT_SECRET, 
        redirection_uri="someuri",
        env=ENVIRONMENT
    )```

**Comment by ibrierley** [comment]
Man thanks
