### ISSUE TITLE
Server responds with error code 500 for what looks like a valid request.

### ISSUE THREAD

**Issue by RoyBellingan** [BingAds/BingAds-Python-SDK#138]
A request like https://gist.github.com/RoyBellingan/28eab4d5912b336ce11737f7e32fcd4e
Is having as response just a 'Internal Server Error' with error code 500
Just a few second before I tried successfully another request, that looks almost the same (but of course for a different report) like https://gist.github.com/RoyBellingan/1842acc042b62b228596310b378cff3b

The code to generate them is the same, only difference is of course the request type and a change in the namespace order

**Comment by RoyBellingan** [comment]
Also this request fails https://gist.github.com/RoyBellingan/d69ff1b5fe9679fb4b01d4f65b3d17a2

**Comment by RoyBellingan** [comment]
Final note I was having also an error doing https://docs.microsoft.com/en-us/advertising/reporting-service/userlocationperformancereportcolumn?view=bingads-13 
And selecting ONLY those column

                ,'AdGroupId'
                ,'TimePeriod'
                , 'MetroArea'
                , 'Impressions'
                , 'Clicks'

By doc TimePeriod alone is enought, but looks like also AccountName, and now is working!

SO the error in this case is not in this SDK but on the server than handle the data, please return a better error description than "Internal Error 500"

**Comment by RoyBellingan** [comment]
Same thing is happening also in other reports, so when the doc says _The report must include at least one of the following attribute columns_ ... well is wrong, please update the doc.

**Comment by eric-urban** [comment]
@RoyBellingan the documentation is updated: "The report must include the following columns. As a general rule, each report must include at least one non-impression share attribute column and at least one performance statistics column." Thanks for your patience!
