### ISSUE TITLE
Unable to get linked accountIds from a particular bing ads account using api

### ISSUE THREAD

**Issue by jatinrajani** [BingAds/BingAds-Python-SDK#142]
Hi,
I am not able to get linked accountIds and their respective campaigns from bing ads account.Please help me i have gone through documentation extensively.

**Comment by jatinrajani** [comment]
Python Code) I am not able to get linked campaignIDs from different bing accountids I have gone through documentation extensively.Please help 
P.S Different bing ads accountIDs means With one account there are multiple bing ads account linked

**Comment by eric-urban** [comment]
@jatinrajani do you have an agency setup and/or are you in the hierarchy beta? In either case please see [Account Hierarchy and User Permissions](https://docs.microsoft.com/en-us/advertising/guides/account-hierarchy-permissions?view=bingads-13) and let me know if you have any follow up questions. If you are using GetAccountsInfo we currently do not return all accounts in the hierarchy, and should close this gap soon i.e., before general availability of hierarchies. I hope this helps!

**Comment by jatinrajani** [comment]
Hi Eric,
Thanks for replying.Basically I can get all linked account ID's,but I can't get the campaign ID's which are linked with these accounts(meaning accounts which run campaigns).I am not able to do using reporting api

**Comment by eric-urban** [comment]
@jatinrajani can you please clarify "can't get the campaign IDs"? Do you have the repro steps for a specific error message or what do you observe? Please feel free to [contact support](https://about.ads.microsoft.com/en-us/microsoft-advertising-support) with your specific account IDs / repro. Thanks

**Comment by qitia** [comment]
close as no update from reporter. feel free to reopen with more detail please @jatinrajani
