### ISSUE TITLE
Error while parsing report containing ResponsiveSearchAds

### ISSUE THREAD

**Issue by sfontana** [BingAds/BingAds-Python-SDK#143]
If an `Ads` report contains a ResponsiveSearchAd [csv_to_field_Rsa_TextAssetLinks](https://github.com/BingAds/BingAds-Python-SDK/blob/master/bingads/v13/internal/extensions.py#L400) fails because the entity being parsed doesn't have all the expected fields (it only has `id`, `text` and `editorialStatus`.

**Comment by qitia** [comment]
Thanks I will double check.

**Comment by qitia** [comment]
Thanks @sfontana, we do not accept PR directly yet. But we have apply your change. Really appreciate.

**Comment by sfontana** [comment]
@qitia I understand, thanks for taking care of it :)
