### ISSUE TITLE
Report types

### ISSUE THREAD

**Issue by Alberick** [BingAds/BingAds-Python-SDK#145]
Hi, This is not an issue if just a question, apologies in advance if this is not the right place to do it. I'm looking for a way to get from the SDK all the reports available and their required columns. How can I do this?
Thank you.

**Comment by qitia** [comment]
I am not sure if you could go [here](https://docs.microsoft.com/en-us/advertising/reporting-service/reporting-data-objects?view=bingads-13) to find the detail?
