### ISSUE TITLE
Readme is unreadable

### ISSUE THREAD

**Issue by rpacheco-aa** [BingAds/BingAds-Python-SDK#15]
This seems to be an email message and not a normal Readme.md. Please provide a valid Readme.md with valid content.

**Comment by imfu** [comment]
Thanks for your response. I will take a look at it..

**Comment by imfu** [comment]
hi, we use reST format for readme file, not md format. If you still have questions, could you please provide more details?
Thanks.
Li.

**Comment by rpacheco-aa** [comment]
Hi,

I think I got the wrong url. I opened the Django Web app and github picks
up an email message as the readme and that's what I was looking at:
https://github.com/BingAds/BingAds-Python-SDK/tree/master/examples/djangowebapp

--
Rui Pacheco

On Tue, May 3, 2016 at 4:19 AM, Kevin <notifications@github.com> wrote:

> hi, we use reST format for readme file, not md format. If you still have
> questions, could you please provide more details?
> Thanks.
> Li.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BingAds/BingAds-Python-SDK/issues/15#issuecomment-216418361>
>

-- 
*This email may contain or reference confidential information and is 
intended only for the individual to whom it is addressed.  Please refrain 
from distributing, disclosing or copying this email and the information 
contained within unless you are the intended recipient.  If you received 
this email in error, please notify us at legal@appannie.com 
<legal@appannie.com>** immediately and remove it from your system.*

**Comment by imfu** [comment]
Hi, sorry for reply late.
MHT file is a format for web pages saved with IE. and the base64 code in that file is a image from the web pages.
You can try to open this file with your browser. suggest to use IE. (also tried chrome in which the image is not showing).
This readme file provides you some information about how the synchronize the database in VS.

Hope this helpful.
Thanks.
Li.

**Comment by imfu** [comment]
close issue. 
@rpacheco-aa  if you still have further questions please feel free to reopen it or open a new issue.
Thanks.
