### ISSUE TITLE
i am a student in python make a speak function and its not work please help me 

### ISSUE THREAD

**Issue by shahidkhan0007** [BingAds/BingAds-Python-SDK#150]
from googletrans import Translator
import win32com.client as wincl
translator = Translator()
def speak(str):
    from win32com.client import Dispatch
    str = translator.translate('str',src='en',dest='hi')
    speak = wincl.Dispatch("SAPI.SpVoice")
    print(Dispatch)

    speak.speak(str)

if __name__ == '__main__':
    speak("Good Morning")

**Comment by qitia** [comment]
This repo is for Microsoft ads SDK. If you have any issue regarding this, please raise here. Otherwise I am afraid you need to ask from other python forum.
