### ISSUE TITLE
CX_Freeze Issue with Bingads on network paths

### ISSUE THREAD

**Issue by techacsshows** [BingAds/BingAds-Python-SDK#153]
I've been having trouble trying to getting the program to run on a network drive. The program works if run locally or run with a driver letter set to the location such as Z:\drive. It seems only bingads module causes this.

For some reason its adding extra slashes to the path. "\\\\\\\\\\\\Drive\\\\folder\\\\folder\\\\lib\\\\bingads\\\\v12\\\\proxies\\\\campaign_management_service.xml". I am using Python 3.6 on Windows 7 and this is my 1st time working on python. Bingads is already included in packages setup. The error code that shows up is [WinError 161].

I added all the packages I need to 'packages' setup. I'm also using CX_Freeze 6.0. Using 6.1 caused the tkinter folders tcl and tk to not copy to the build directory.

OS:Win 7 64 bit

Python ver: 3.6

[Error](https://i.imgur.com/LjdcWMr.png)
[Setup.py](https://i.imgur.com/Q5Rm5Ih.png)

**Comment by qitia** [comment]
could you please check if [this](https://social.msdn.microsoft.com/Forums/en-US/ac61a1e0-381a-4b4c-ba88-b958dbdce3e1/cxfreeze-exe-not-working-on-nonmapped-network-drive?forum=BingAds) helps?
