### ISSUE TITLE
CampaignManagementService - GetCampaignsByAccountId : InvalidAccountId

### ISSUE THREAD

**Issue by melbadry** [BingAds/BingAds-Python-SDK#154]
I'm trying to get an account's campaigns using the following 
```
    campaign_service =  ServiceClient(
        service='CampaignManagementService', 
        version=settings.API_VERSION,
        authorization_data=authorization_data,
        environment=settings.ENVIRONMENT
        )
    search_campaings_response = campaign_service.GetCampaignsByAccountId(
        AccountId=account_id,
        CampaignType='Search')
```
where the account_id is the first output of 
```
    Search_accounts_response = customer_service.SearchAccounts(
            PageInfo=paging,
            Predicates=predicates
        )
```
but I always get the response 

```
<suds.sax.document.Document object at 0x105d50310>
[(AdApiError){
   Code = "119"
   Detail = None
   ErrorCode = "InvalidAccountId"
   Message = "The account ID is invalid."
 }]
```

I've checked the frontend and made sure the account_id exists and Active but still not sure why I keep getting the InvalidAccount error -- please advise. 

Thanks!

**Comment by qitia** [comment]
Could you please share the trackingid/requestid? @melbadry

**Comment by melbadry** [comment]
hi @qitia , how can I get either trackingid or requestid?

**Comment by qitia** [comment]
@melbadry could [this](https://docs.microsoft.com/en-us/advertising/guides/handle-service-errors-exceptions?view=bingads-13) help?

**Comment by melbadry** [comment]
can't find error code 119 in it, the strange thing is that I can get the list of available accounts and Ids. but when using any of these Ids I get the error : { Code = "119" Detail = None ErrorCode = "InvalidAccountId" Message = "The account ID is invalid." }

**Comment by qitia** [comment]
aah, maybe the link I posted just now is not accurate. I meant to say if it helps to find the tracking ID. maybe you can refer to this [ApiFault Data Object](https://docs.microsoft.com/en-us/advertising/customer-management-service/apifault?view=bingads-13) to find the tracking id?

**Comment by melbadry** [comment]
enabling the logging with INFO level did the trick 
TrackingId: b0086b88-3e0f-4979-8dfa-3459ba44decf

**Comment by qitia** [comment]
Thanks @melbadry , we will check and come back.

**Comment by qitia** [comment]
The log and the error code shows that the accountid is not a valid one from what I can see.

The Account ID should be a "long" value. Does your account ID has the right format? Could you please also send the tracking id for your SearchAccounts call?

**Comment by melbadry** [comment]
Thank you for checking.
I think the accountID in the right format 
Tracking id for SearchAccounts:  09a88d08-5af8-4827-8ca1-bfe597705743

will follow the example and let you know if I'm still facing the same issue. 

thank you.

**Comment by qitia** [comment]
@melbadry  is this issue still repro?

**Comment by melbadry** [comment]
hi @qitia , sadly yes I'm still facing it, and tried a couple of things with no luck. so still trying to figure out what happens and why

**Comment by qitia** [comment]
Hi @melbadry , how is it now? still repro? Could you please contact the support team and let's know the accounID you are using?

**Comment by melbadry** [comment]
Hi @qitia, it's still acting the same way. will reach out to the support team and share the details of the request. 

Thank you :)

**Comment by qitia** [comment]
did you reach support team @melbadry? are you still facing this issue?

**Comment by qitia** [comment]
I will close it as of now since no update from reporter and not enough info for investigation. Feel free to reopen if you face the same issue with more detial @melbadry
