### ISSUE TITLE
AccountPerformanceReportRequest / Others return different number of rows between executions

### ISSUE THREAD

**Issue by sleonte0182** [BingAds/BingAds-Python-SDK#155]
Hi, 
I know this is not only related to this SDK, but if any one of you have had this problem I would appreciate your input.

I have been submitting Different kind of Reports for multiple AccountIds being in my scope like this:

scope.AccountIds {'long': [N1, N2, N3, N4, N5]}

Sometimes it returns me all data for all the account ids but if I execute the code again it will give me maybe 3-4 of them.

This behavior doesn't happen if I do it through the Web UI.

If you need more information please let me know.

Any idea?

**Comment by qitia** [comment]
if you could share the trackingid/requestid, that will be helpful.

**Comment by qitia** [comment]
@sleonte0182  are you still facing this issue? please let me know trackingid/requestid or step to repro in case of yes.

**Comment by qitia** [comment]
close as no update from reporter. Feel free to reopen with more detail please @sleonte0182
