### ISSUE TITLE
v13:ReportRequest: Invalid enum value 'AthensBuckarestIstanbul'

### ISSUE THREAD

**Issue by sm5111** [BingAds/BingAds-Python-SDK#157]
Full error message:
Server raised fault: 'The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter https://bingads.microsoft.com/Reporting/v13:ReportRequest. The InnerException message was 'Invalid enum value 'AthensBuckarestIstanbul' cannot be deserialized into type 'Microsoft.AdCenter.Advertiser.Reporting.Api.DataContracts.Enum.ReportTimeZone'. Ensure that the necessary enum values are present and are marked with EnumMemberAttribute attribute if the type has DataContractAttribute attribute.'.  Please see InnerException for more details.'

**Comment by qitia** [comment]
This is not the SDK issue. I think this timezone is not supported from backend(reporting service). Maybe you want to raise request from [here](https://answers.microsoft.com/en-us/bing/forum/bing_ads-bing_adscustomers?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1)
