### ISSUE TITLE
submit_and_download()

### ISSUE THREAD

**Issue by nibakai** [BingAds/BingAds-Python-SDK#16]
Does the commented code:

if download_status.status == 'Completed':
            break

at line 434 from https://github.com/BingAds/BingAds-Python-SDK/blob/master/examples/BingAdsPythonConsoleExamples/BingAdsPythonConsoleExamples/v9/ReportRequests.py still valid? I noticed there not a such status called "Completed". It seems like it is called "Success" now.

**Comment by eric-urban** [comment]
Thanks for catching this! Have updated the sample code.
