### ISSUE TITLE
'bingads.v13.reporting.reporting_service_manager' has no attribute 'download_file'

### ISSUE THREAD

**Issue by jinwang7** [BingAds/BingAds-Python-SDK#163]
**Hi,

I am following one of examples to pull a report. Code is here: https://github.com/BingAds/BingAds-Python-SDK/blob/master/examples/v13/report_requests.py.

I was successfully pulling a report using this code multiple times before by running the python script in Atom. However, all of the sudden when I tried to run the script from commend line it failed today and gave me an error message 'AttributeError: module 'bingads.v13.reporting.reporting_download_parameters' has no attribute 'report_request' '.  The download function did not work. I check the code that was identical to with which I was able to run it before. 

Then I tried to run the script back in Atom, it failed too and generated the same error above. Very odds. 

I guess it's a name conversion conflicts but it looks like the other issue. 

Could you help?

Thanks

Jin

**Comment by qitia** [comment]
hi @jinwang7 , which version are you using? I found [this class ](https://github.com/BingAds/BingAds-Python-SDK/blob/f63a8ae3afa049ef710fbccb20819185b027cd57/bingads/v13/reporting/reporting_download_parameters.py#L97)remain unchanged for a long time.

**Comment by qitia** [comment]
close as no update from reporter and no enough info for investigation. Feel free to reopen with more detail please @jinwang7
