### ISSUE TITLE
OAuthTokenRequestException when `require_live_connect` set to True

### ISSUE THREAD

**Issue by cosimon** [BingAds/BingAds-Python-SDK#164]
When authenticating with `OAuthWebAuthCodeGrant` and `require_live_connect` is set to True, I get the an OAuthTokenRequestException with the error message:
```
error_code: invalid_scope, error_description: The provided value for the input parameter 'scope' is not valid. The scope 'bingads.manage' is not configured for this tenant.
```

This happens from version `13.0.4` onwards. It does not happen with version `13.0.3`

**Comment by qitia** [comment]
please refer to [this example](https://github.com/BingAds/BingAds-Python-SDK/blob/main/examples/v13/auth_helper.py) for how to authenticate. or you can share our code piece for investigation.
