### ISSUE TITLE
Seeing <urlopen error timed out> consistently on sandbox.

### ISSUE THREAD

**Issue by msaparito** [BingAds/BingAds-Python-SDK#168]
Running bulk uploads for offline conversions to sandbox for testing an environment's connectivity and noticing that once we enter the example code:

File: bulk_offline_conversions.py Line: 38
```
        download_entities=write_entities_and_upload_file(
            bulk_service_manager=bulk_service_manager, 
            upload_entities=upload_entities)
```

The fault occurs. We know our refresh_token, client_id, developer_token should be fine as we manually request a new refresh token in our pipeline prior to this. 2 days ago we did not receive this error, we are just trying to see if it's the sandbox or not.

Our stack output:
```
Loading the web service client proxies...
-----
Applying offline conversions...
<urlopen error [Errno 60] Operation timed out>
```

SDK Version: bingads==13.0.5
bing_sandbox_developer_token=BBD37VB98
bing_sandbox_client_id=db41b09d-6e50-4f4a-90ac-5a99caefb52f
bing_sandbox_refresh_secret='M.R0_SN3.-AUpGS....'

**Comment by xtan9** [comment]
I have the same issue.

**Comment by msaparito** [comment]
I have checked and production entries run as expected. I assume this is an error with sandbox's endpoint.

**Comment by qitia** [comment]
close as of now. Please reopen if you see the same issue.
