### ISSUE TITLE
How to modify Auth_Helper.py to include all the active accounts ?

### ISSUE THREAD

**Issue by nandinilimbaskar** [BingAds/BingAds-Python-SDK#170]
Currently I'm manually entering account numbers like
authorization_data.account_id=accounts[ 'xxxx','yyyy']
How to modify the code so that the array will have all the current accounts for the user ID ? 

TYIA !!

**Comment by qitia** [comment]
Auth_Helper.py is just a sample, you can do whatever you want to modify it
