### ISSUE TITLE
Robux Scam??

### ISSUE THREAD

**Issue by LolalrikofficialYT** [BingAds/BingAds-Python-SDK#171]
Why Why Why Microsoft did u remove the free robux , and also its not fair that u guys are not allowing other countries to have it. Is this a joke , I waited on ur website for 3 hours after I received the free 100 robux but it showed me an error , and it said that this product is unavailable , wtf is wrong with guys , pls send me the robux code  ASAP, 
I have the right to get it cause I did all the steps . Send me the code here : ralrik31@outlook.com , I better see my robux code in my outlook email by tommorow 31/12/2020

It better be there 😠

I did not sit there in ur stupid website for 3 hours  to see this error.

**Comment by qitia** [comment]
please contact our support team if you have anything concern with Bing Ads SDK. please do not raise unrelated questions here.
