### ISSUE TITLE
Support for Python 3.9

### ISSUE THREAD

**Issue by kater169** [BingAds/BingAds-Python-SDK#178]
Hi,
could you please add Python 3.9.1 support? Right now there is now compatible version with pip. Thx

pip 21.0.1 

pip install bingads

ERROR: Could not find a version that satisfies the requirement bingads
ERROR: No matching distribution found for bingads

**Comment by qitia** [comment]
hi @kater169, this is the first time I hear this. I tried and succeed installing for python 3.9.1
![image](https://user-images.githubusercontent.com/29188289/116061395-604ecb00-a6b5-11eb-9228-824e30b2dc76.png)

I am using pip 21.1 FYI

**Comment by kater169** [comment]
ok, thx now it works.
