### ISSUE TITLE
Load report without creating local file Bing Ads API

### ISSUE THREAD

**Issue by pnd-kstankevich** [BingAds/BingAds-Python-SDK#179]
Is it possible to download the report from Bing Ads API as an in-memory object WITHOUT loading it locally as a file? I would be grateful if the code snipper will be in Python. 

The link from the documentation: https://github.com/BingAds/BingAds-Python-SDK/blob/main/examples/v13/report_requests.py **line 65 downloads file and then reads from it.**

**Comment by qitia** [comment]
no, currently it always download the result into a file. in the doc you mentioned above, you can find comments from line 143 as
```
You can get a Report object by submitting a new download request via ReportingServiceManager. 
Although in this case you will not work directly with the file, under the covers a request is 
submitted to the Reporting service and the report file is downloaded to a local directory. 
```
Report reader only accept a file and parse it as Report object as of now. You can use the same concept as [here](https://github.com/BingAds/BingAds-Python-SDK/blob/4f1ed7f3eb567b0bc826b17b5991e0d01be82743/examples/v13/report_requests.py#L142) without knowing about the result file. Is there any specific reason you do not want a file?

**Comment by qitia** [comment]
will close this issue. please reopen or create new one for any further concern.
