### ISSUE TITLE
"from bingads import ServiceClient" fails: bingads/v13/proxies/sandbox/campaignmanagement_service.xml not found

### ISSUE THREAD

**Issue by Dremet** [BingAds/BingAds-Python-SDK#181]
Since today, we get an error when importing the Service Client. Our anaconda python environment looks like this:

Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
astroid                   2.4.0                    py38_0
bcrypt                    3.1.7            py38h7b6447c_1
bingads                   13.0.9                   pypi_0    pypi
blas                      1.0                         mkl
ca-certificates           2020.1.1                      0
certifi                   2020.4.5.1               py38_0
cffi                      1.14.0           py38he30daa8_1
chardet                   3.0.4           py38h06a4308_1003
click                     7.1.2              pyhd3eb1b0_0
cryptography              2.9.2            py38h1ba5d50_0
dacite                    1.6.0                    pypi_0    pypi
etl-helpers               2.0.0                    pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
idna                      2.9                        py_1
intel-openmp              2020.1                      217
isort                     4.3.21                   py38_0
jinja2                    2.11.3                   pypi_0    pypi
lazy-object-proxy         1.4.3            py38h27cfd23_2
ld_impl_linux-64          2.33.1               h53a641e_7
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libsodium                 1.0.16               h1bed415_0
libstdcxx-ng              9.1.0                hdf63c60_0
markupsafe                1.1.1                    pypi_0    pypi
mccabe                    0.6.1                    py38_1
mkl                       2020.1                      217
mkl-service               2.3.0            py38he904b0f_0
mkl_fft                   1.0.15           py38ha843d7b_0
mkl_random                1.1.0            py38h962f231_0
ncurses                   6.2                  he6710b0_1
numpy                     1.18.1           py38h4f9e942_0
numpy-base                1.18.1           py38hde5b4d6_1
openssl                   1.1.1g               h7b6447c_0
pandas                    1.0.3            py38h0573a6f_0
paramiko                  2.7.2                    pypi_0    pypi
pip                       20.0.2                   py38_3
pycparser                 2.20                       py_2
pylint                    2.5.0                    py38_1
pynacl                    1.3.0            py38h7b6447c_0
pyopenssl                 19.1.0             pyhd3eb1b0_1
pysocks                   1.7.1            py38h06a4308_0
python                    3.8.2               hcff3b4d_14
python-dateutil           2.8.1              pyhd3eb1b0_0
pytz                      2020.1                     py_0
pyyaml                    5.3.1            py38h7b6447c_0
readline                  8.0                  h7b6447c_0
requests                  2.23.0                   py38_0
setuptools                46.2.0                   py38_0
six                       1.14.0           py38h06a4308_0
sqlite                    3.31.1               h62c20be_1
suds-jurko                0.6                      pypi_0    pypi
tk                        8.6.8                hbc83047_0
toml                      0.10.0             pyh9af5748_0
urllib3                   1.25.8                   py38_0
wheel                     0.34.2                   py38_0
wrapt                     1.11.2           py38h7b6447c_0
xz                        5.2.5                h7b6447c_0
yaml                      0.1.7                had09818_2
zlib                      1.2.11               h7b6447c_3

And the error occurs already on import:

Python 3.8.2 (default, May  7 2020, 20:00:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bingads import ServiceClient
Traceback (most recent call last):
  File "/home/dremet/.conda/envs/bing_download/lib/python3.8/urllib/request.py", line 1476, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [Errno 2] No such file or directory: '//home/dremet/.conda/envs/bing_download/lib/python3.8/site-packages/bingads/v13/proxies/sandbox/campaignmanagement_service.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dremet/.conda/envs/bing_download/lib/python3.8/site-packages/bingads/__init__.py", line 3, in <module>
    from .service_client import *
  File "/home/dremet/.conda/envs/bing_download/lib/python3.8/site-packages/bingads/service_client.py", line 299, in <module>
    _CAMPAIGN_MANAGEMENT_SERVICE_V13 = Client(
  File "/home/dremet/.conda/envs/bing_download/lib/python3.8/site-packages/suds/client.py", line 115, in __init__
    self.wsdl = reader.open(url)
  File "/home/dremet/.conda/envs/bing_download/lib/python3.8/site-packages/suds/reader.py", line 150, in open
    d = self.fn(url, self.options)
  File "/home/dremet/.conda/envs/bing_download/lib/python3.8/site-packages/suds/wsdl.py", line 136, in __init__
    d = reader.open(url)
  File "/home/dremet/.conda/envs/bing_download/lib/python3.8/site-packages/suds/reader.py", line 74, in open
    d = self.download(url)
  File "/home/dremet/.conda/envs/bing_download/lib/python3.8/site-packages/suds/reader.py", line 92, in download
    fp = self.options.transport.open(Request(url))
  File "/home/dremet/.conda/envs/bing_download/lib/python3.8/site-packages/suds/transport/https.py", line 62, in open
    return HttpTransport.open(self, request)
  File "/home/dremet/.conda/envs/bing_download/lib/python3.8/site-packages/suds/transport/http.py", line 67, in open
    return self.u2open(u2request)
  File "/home/dremet/.conda/envs/bing_download/lib/python3.8/site-packages/suds/transport/http.py", line 132, in u2open    return url.open(u2request, timeout=tm)
  File "/home/dremet/.conda/envs/bing_download/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/dremet/.conda/envs/bing_download/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/dremet/.conda/envs/bing_download/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/dremet/.conda/envs/bing_download/lib/python3.8/urllib/request.py", line 1454, in file_open
    return self.open_local_file(req)
  File "/home/dremet/.conda/envs/bing_download/lib/python3.8/urllib/request.py", line 1493, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory: '//home/dremet/.conda/envs/bing_download/lib/python3.8/site-packages/bingads/v13/proxies/sandbox/campaignmanagement_service.xml'>

**As you released a new version today, I suspect this is a bug?**

**Comment by djuery** [comment]
Exactly the same issue here, and it's only happening since 4 hours almost, which corresponds to the latest commit in the project. Please let us know whenever this gets fixed!

**Comment by Dremet** [comment]
Downgraded to 13.0.8 and everything works fine again.

**Comment by qitia** [comment]
hi @djuery  @Dremet, are you using version 13.0.9? or just copy code from this repo? we made a change to service url definition but it should transparent to client. May I know your use case?

**Comment by Dremet** [comment]
> hi @djuery @Dremet, are you using version 13.0.9? or just copy code from this repo? we made a change to service url definition but it should transparent to client. May I know your use case?

I posted my python environment. You see that I used 13.0.9 there. The use case should not be relevant as you can simply replicate it by trying to import the ServiceClient as described above.

**Comment by qitia** [comment]
Sorry guys, we just released new version 13.0.9.1 to fix this issue. Please give it a try.
