### ISSUE TITLE
New Scope question (msads.manage)

### ISSUE THREAD

**Issue by AlexanderCord** [BingAds/BingAds-Python-SDK#183]
Hello!

I've read this in blog
https://techcommunity.microsoft.com/t5/bing-ads-api-blog/new-requirements-for-multi-factor-authentication/ba-p/2234100

Could you tell me please, when is this new scope (msads.manage) going to be implemented in library? 
I've searched for it in this repository (and in libraries for other languages as well), and haven't found it.

Do we need to fix it on our side? Wanted to know in advance to prepare and get it done.

Thank you.

**Comment by qitia** [comment]
Hi there, the new scope msads.manage is not supported in the lib yet. we are targeting implement it in next version 13.0.10, please stay tuned.

**Comment by AlexanderCord** [comment]
Got it, thank you!
