### ISSUE TITLE
Bing Ads API v13 MFA breaking changes

### ISSUE THREAD

**Issue by JohnWE** [BingAds/BingAds-Python-SDK#184]
It looks like the Bing Ads API is going to be requiring MFA on August 1st.  To support this, there needs to be a change from `ads.manage` to `msads.manage`

See: https://docs.microsoft.com/en-us/advertising/guides/release-notes?view=bingads-13

Is there a plan to update this library to support that, or should we do it manually in our project?

https://github.com/BingAds/BingAds-Python-SDK/blob/4f1ed7f3eb567b0bc826b17b5991e0d01be82743/bingads/authorization.py#L675

**Comment by JianyunZhao** [comment]
SDK 13.0.10 was released last week to support new OAuthScope msads.manage, please have a try.
