### ISSUE TITLE
Web service reported a SOAP processing fault using an unexpected HTTP status code 200. Reporting as an internal server error.

### ISSUE THREAD

**Issue by yuzeh** [BingAds/BingAds-Python-SDK#190]
Using 13.0.11.

Logs from the Airflow instance:

```
[2021-08-25 23:09:50,622] {{client.py:668}} WARNING - Web service reported a SOAP processing fault using an unexpected HTTP status code 200. Reporting as an internal server error.
[2021-08-25 23:09:50,623] {{client.py:694}} ERROR - <suds.sax.document.Document object at 0x7fd6c4fa2f10>
[2021-08-25 23:09:50,623] {{taskinstance.py:1462}} ERROR - Task failed with exception
Traceback (most recent call last):
  File REDACTED user code
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/bingads/service_client.py", line 272, in __call__
    raise ex
  File "/usr/local/airflow/.local/lib/python3.7/site-packages/bingads/service_client.py", line 264, in __call__
    response = self.service_client.soap_client.service.__getattr__(self.name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/usr/local/lib/python3.7/site-packages/suds/client.py", line 621, in send
    original_soapenv=original_soapenv)
  File "/usr/local/lib/python3.7/site-packages/suds/client.py", line 670, in process_reply
    raise WebFault(fault, replyroot)
suds.WebFault: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 5baaef1d-6e41-4280-a3ab-3a110292032f.'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File REDACTED user code
RuntimeError: [(AdApiError){
   Code = "0"
   Detail = None
   ErrorCode = "InternalError"
   Message = "An internal error has occurred."
 }]
```

We were calling the `GetAdsByAdGroupId` endpoint when this occurred.

I have two questions:
1. How do I access the SOAP fault details?
2. Why is this error occurring? I would think a 200 should be an expected status.

**Comment by qitia** [comment]
can you share the payload? or do you have a requestid/trackingid? which could be found from the response. If you debug, you could find detailed error message from the response.

**Comment by qitia** [comment]
close as lack of valid detail. Please reopen with more detail if you face the same issue.

**Comment by asrivastavsprighub** [comment]
I am also facing same issue 

Server raised fault: Invalid client data. Check the SOAP fault details for more information. TrackingId: ae2cf7a5-8ea4-4d15-99e6-89250223639e

tracking id also added here. please help me

**Comment by qitia** [comment]
Checked the log and seems like you are still using old way of OAuth. Microsoft Ads has [enforced MFA](https://docs.microsoft.com/en-us/advertising/guides/authentication-oauth-mfa?view=bingads-13) since JUNE 1  2022. Can you please double confirm you already adopt that?

**Comment by hassan1731996** [comment]
I'm facing the same issue atm 
suds.WebFault: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 0b0f43fa-1b5f-4a14-9946-960d29c40966.'
tracking id also added here. please help me

**Comment by shpilievoi29** [comment]
@qitia suds.WebFault: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 29a587c6-de6c-4146-a4e5-aa2ef6a9dbbc.'
Help Me

**Comment by SelfTaughtCoder78704** [comment]
any updates I have the same error. Was working one minute, and then stopped the next.
Error: 
Web service reported a SOAP processing fault using an unexpected HTTP status code 200. Reporting as an internal server error.
^CTraceback (most recent call last):
  File "/var/www/vhosts/tools.fivemill.com/scripts/bingAdsApi_v13.py", line 484, in __setCustomerId
    user = self.getCustomerService().GetUser()
  File "/var/www/vhosts/tools.fivemill.com/python3/lib/python3.8/site-packages/bingads/service_client.py", line 323, in __call__
    raise ex
  File "/var/www/vhosts/tools.fivemill.com/python3/lib/python3.8/site-packages/bingads/service_client.py", line 315, in __call__
    response = self.service_client.soap_client.service.__getattr__(self.name)(*args, **kwargs)
  File "/var/www/vhosts/tools.fivemill.com/python3/lib/python3.8/site-packages/suds/client.py", line 566, in __call__
    return client.invoke(args, kwargs)
  File "/var/www/vhosts/tools.fivemill.com/python3/lib/python3.8/site-packages/suds/client.py", line 708, in invoke
    result = self.send(soapenv, timeout=timeout)
  File "/var/www/vhosts/tools.fivemill.com/python3/lib/python3.8/site-packages/suds/client.py", line 756, in send
    return self.process_reply(reply.message, None, None)
  File "/var/www/vhosts/tools.fivemill.com/python3/lib/python3.8/site-packages/suds/client.py", line 817, in process_reply
    raise WebFault(fault, replyroot)
suds.WebFault: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 2f350bd4-ddfe-4b59-9a8c-f3b9ec113efb.'

**Comment by jasonlu2023** [comment]
@qitia we are trying to make api call for offline conversion, we followed the web sample code authenticated the request. It can fetch the tokens and account info successfully. When we try to make offline api call, we got this error. Could you help check what's the exactly issue? Thanks. 

Web service reported a SOAP processing fault using an unexpected HTTP status code 200. Reporting as an internal server error.
WebFault Error:Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 44960e29-f69d-44b1-bb2a-65bb3d288763.'

**Comment by qitia** [comment]
Invalid AccountId and Invalid CustomerId Please reach out to  Microsoft Advertising Technical Support <adsupport@microsoft.com> for help for this kind of issue

**Comment by mengbiping** [comment]
@qitia please help with this one, when I'm trying to update device bid adjustment 
Web service reported a SOAP processing fault using an unexpected HTTP status code 200. Reporting as an internal server error.
*** suds.WebFault: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 3c87c4f2-fd69-413d-a5b8-5b5b13b1a0cd.'

**Comment by qitia** [comment]
Please reach out to support team for help [adsupport@microsoft.com](mailto:adsupport@microsoft.com) @mengbiping

**Comment by mc51** [comment]
Experiencing the same error message when trying to work with OfflineConversion upload. Could you please tell me what `TrackingId: c9f5877f-9498-47ab-87e4-84b7e077ee87.` translates to @qitia?

**Comment by qitia** [comment]
Provider.Authorize failed with message The user 108341858 is not authorized to do CampaignManagementFullControl on resource 1717516

Qingjun

**Comment by sunilchowdary9** [comment]
@qitia please help me with this issue,
I was tring to download the campaign performance report and facing this error
"Web service reported a SOAP processing fault using an unexpected HTTP status code 200. Reporting as an internal server error.
An error occured in downloading campaign report:Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: b8e8ea9f-0ad1-46d5-a5a9-9c5c6917e668.'
Error occured:Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: b8e8ea9f-0ad1-46d5-a5a9-9c5c6917e668.'
MICROSOFT_ADVERTISING_MAIN : data extraction processing Failed !!!!: (<class 'suds.WebFault'>, WebFault("Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: b8e8ea9f-0ad1-46d5-a5a9-9c5c6917e668.'"), <traceback object at 0x788eae464300>)"

**Comment by sunilchowdary9** [comment]
Hi @qitia Please help me with this 

I was trying to download the Keyword performance report and getting this error
"Web service reported a SOAP processing fault using an unexpected HTTP status code 200. Reporting as an internal server error.
An error occured in downloading keyword report:Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 5990d89b-2dd7-4f58-902b-7bda174bdb1d.'
Error occured:Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 5990d89b-2dd7-4f58-902b-7bda174bdb1d.'
MICROSOFT_ADVERTISING_MAIN : data extraction processing Failed !!!!: (<class 'suds.WebFault'>, WebFault("Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 5990d89b-2dd7-4f58-902b-7bda174bdb1d.'"), <traceback object at 0x76c254376640>)"

**Comment by qitia** [comment]
@sunilchowdary9 

"The specified report request does not specify measurement columns (at least one is required). Please submit a report request with the required columns for this report type, and optionally additional columns that are to be included in the report."

**Comment by mandy-elastiq** [comment]
Hello @qitia , 
We are getting the below error:
Web service reported a SOAP processing fault using an unexpected HTTP status code 200. Reporting as an internal server error.
WebFault Exception: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 426bee64-121c-405b-9c0c-aeed0a426a91.'

Can you please help us over here

**Comment by qitia** [comment]
@mandy-elastiq 

"The accountId is invalid"

**Comment by dk7998** [comment]
> @mandy-elastiq
> 
> "The accountId is invalid"

Hi - Is there a way for us to get these error details using the tracking_id, we are using bingads python pkg?

**Comment by qitia** [comment]
no so far. let me think about this.

**Comment by shachitaku** [comment]
Hi @qitia 
I'm working with OfflineConversion upload and I'm getting an error below:
```
Web service reported a SOAP processing fault using an unexpected HTTP status code 200. Reporting as an internal server error. 
Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 325170bd-7a8b-4b34-8c02-f9022747f533.' 
```

could you tell me the reason for this?

**Comment by qitia** [comment]
"Parameter 'OfflineConversions' is required and hasn't been found." @shachitaku Seems like you are trying to invoke api: [ApplyOfflineConversions](https://learn.microsoft.com/en-us/advertising/campaign-management-service/applyofflineconversions?view=bingads-13), you need to provide valid OfflineConversions.

**Comment by shachitaku** [comment]
@qitia 
Thank you for your swift response!
The value I provided was indeed inappropriate, and I fixed it a few hours ago.
Now I'm getting SOAP response as follows with no BatchError elements inside.

```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Header>
        <h:TrackingId xmlns:h="https://bingads.microsoft.com/CampaignManagement/v13">9eaafe65-35de-4ecc-89e6-fe53c8751b30</h:TrackingId>
    </s:Header>
    <s:Body>
    <ApplyOfflineConversionsResponse xmlns="https://bingads.microsoft.com/CampaignManagement/v13">
        <PartialErrors xmlns:i="http://www.w3.org/2001/XMLSchema-instance"/>
    </ApplyOfflineConversionsResponse>
    </s:Body>
</s:Envelope>
```

However, the issue is that, when I go to the conversion goals page in Microsoft Advertising, the conversions I uploaded do not seem to be reflected(even after a few hour wait). I'm not sure what I'm doing wrong since I'm not receiving errors anymore. 

(ref photo) The 4th goal from the top is the offline conversion goal I'm uploading to, but the tracking status shows nothing.
<img width="2557" alt="362171824-909e8a18-0191-4954-809d-15f2186269a7" src="https://github.com/user-attachments/assets/998f5832-6093-4b00-afa2-13bf74a2fa6e">

Would you be able to track why my ApplyOfflineConversionsRequest that returns 200 doesn't reflect on Microsoft Advertising using the tracking id (i.e. `9eaafe65-35de-4ecc-89e6-fe53c8751b30`)?

**Comment by qitia** [comment]
@shachitaku  per the feature owner:
It’s by design. Offline Conversion Goal doesn't have tracking status.
The customer can see the results in All Conv column in Goal page.
The response code 200 means what the customer uploaded passed MT validation and it went to downstream. Once the attribution analysis is complete, All Conv column will be updated.

**Comment by pepa-from-meiro** [comment]
Hi @qitia I am getting this error: `suds.WebFault: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: cfe0a75e-cf64-4fe0-8321-0191f9943d83.'` Could please give me more detailed information about this error?

**Comment by eqm42** [comment]
Hi @qitia
I'm working with OfflineConversion upload and I'm getting an error below:

```
Web service reported a SOAP processing fault using an unexpected HTTP status code 200. Reporting as an internal server error.
Error uploading conversions: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: b3486e02-0abd-45db-b0ee-61e121b837c2.'
```


could you tell me the reason, please?

**Comment by harsh-conversio** [comment]
@qitia i'm facing same issues, where i'm getting the customers list.

Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 007441ba-0d5c-462a-a64a-01907f90c6aa.'

**Comment by Valkrysa** [comment]
@qitia hello! I am encountering this issue with one of my offline conversion events but not the other when calling ApplyOfflineConversions

WARNING - Web service reported a SOAP processing fault using an unexpected HTTP status code 200. Reporting as an internal server error.
suds.WebFault: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 846c6949-d7de-43e4-aba8-f24c371dacc6.'

Could I get some help as to what that tracking code refers to us doing wrong? Also was a way ever added so that we could check on the error meanings ourselves?
The only difference I can think of between my two conversion goals is the one that is failing is of category type "Other" whereas the successful conversion goal is not set to "Other". Maybe "Other" requires something special to be done?
