### ISSUE TITLE
error in unmarshalling request. The schema is missing for PauseAIMAdGroupIfAllAudienceCriterionNotImported.

### ISSUE THREAD

**Issue by sharangdeo** [BingAds/BingAds-Python-SDK#193]
While getting google_import_status for a certain sync_id, the unmarshalling bit of the request was broken. It was last tested and was working over 2 weeks ago. There seems to be an issue with the schema.

This is some [example code to replicate the issue](https://docs.google.com/document/d/1Zkqc3vMO4KsCMR6Snm5oT4eEaIfbwc4lxNnAlt3eG-o/edit?usp=sharing) I came across

Here is the [error traceback](https://docs.google.com/document/d/1P_aDLC2w9CneXSGmgRygIIAAXifdJHmTom4cWoEMyuI/edit?usp=sharing) for reference

**Comment by qitia** [comment]
hi @sharangdeo, I confirm this is a regression from backend. I will update this when it is got fixed.

**Comment by qitia** [comment]
this should have been fixed. reopen in case you see it again @sharangdeo

**Comment by sharangdeo** [comment]
Thank you @qitia . I can confirm it is working as expected now!
