### ISSUE TITLE
bingads report download Error: There was an error deserializing the object, cannot be parsed as the type 'Int32' #148

### ISSUE THREAD

**Issue by Caspar0-0** [BingAds/BingAds-Python-SDK#195]
There was an error deserializing the object of type Microsoft.AdCenter.Advertiser.Reporting.Api.DataContracts.Request.ReportRequest. The value '' cannot be parsed as the type 'Int32'.'.

**Comment by traas87** [comment]
Having the same issue. Trying to pull reports using the example code. Error always starts by referencing the line where "download_results" (or another option) is called. Also throws an unknown webfault exception after.

**Comment by traas87** [comment]
This can be closed. The issue was solved by qitia last year. https://github.com/BingAds/BingAds-Python-SDK/issues/148#issuecomment-645343286 

For whatever reason adding in     
   ` time.CustomDateRangeStart = None
    time.CustomDateRangeEnd = None`
in the get_report_request function fixes the issue.

**Comment by qitia** [comment]
@Caspar0-0 which version of SDK are you using? does #148 the same as yours?
