### ISSUE TITLE
Reporting Api has become slow

### ISSUE THREAD

**Issue by keshavgoyal2807** [BingAds/BingAds-Python-SDK#196]
I am using reporting api to download reports for different accounts but now it is taking much longer then before. It used to take less than 5 min earlier but now it is taking around 30-35 minutes. 
Could you please help me on this.

**Comment by leongersen** [comment]
I'm seeing this as well, as of ~ 2021-12-02 17:00 UTC. DNS resolution and TCP connect are fast, but the SSL handshake with `reporting.api.bingads.microsoft.com:443` is very slow and often times out or fails.

**Comment by keshavgoyal2807** [comment]
Now it is working fine.
