### ISSUE TITLE
BULK API: how to download all data in Keyword entity?

### ISSUE THREAD

**Issue by Greta991** [BingAds/BingAds-Python-SDK#203]
Hello,
I used the Bulk API. In particular, i downloaded a CSV containing the keywords of my Bing Ads Account.
The code is as follows:

`

        bulk_service_manager = BulkServiceManager(
            authorization_data=authorization_data,
            poll_interval_in_milliseconds=5000,
            environment=environment,
        )

        # SubmitDownloadParameters is used for Option B and Option C below.
        submit_download_parameters = SubmitDownloadParameters(
            campaign_ids=None,
            data_scope=['EntityData'],
            download_entities=['Keywords'],
            file_type=FILE_TYPE,
            last_sync_time_in_utc=last_14_days
        )
`

But in the CSV file there are only these populated data: Type, Status, Id, Parent Id, Campaign, Ad Group, Modified Time.

Many other data are missing such as the **match type** data (extact, broad and phrase). Why? Did I fill in the request wrong?
Thank you!

**Comment by Ritik262** [comment]
but how to get msclkid in bing ads

**Comment by Ritik262** [comment]
how to fetch msclkid in bing ads using python api

**Comment by qitia** [comment]
no you cannot download msclickid from api/sdk.
