### ISSUE TITLE
Timezone error for America/Boise

### ISSUE THREAD

**Issue by shs-odoo** [BingAds/BingAds-Python-SDK#204]
for https://github.com/BingAds/BingAds-Python-SDK/blob/main/examples/v13/customer_signup.py when i am trying with timezone America/Boise facing an error 

unhandled exception: Server raised fault: 'The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter https://bingads.microsoft.com/Customer/v13:Account. The InnerException message was 'Invalid enum value 'MountainTime_US_Canada' cannot be deserialized into type 'Microsoft.AdCenter.ClientCenter.Api.DataContract.v13.Entity.TimeZoneType'. Ensure that the necessary enum values are present and are marked with EnumMemberAttribute attribute if the type has DataContractAttribute attribute.'.  Please see InnerException for more details.

**Comment by shs-odoo** [comment]
@qitia  can you please check

**Comment by qitia** [comment]
can you try 'MountainTimeUSCanada' per the [document](https://docs.microsoft.com/en-us/advertising/customer-management-service/timezonetype?view=bingads-13)

**Comment by balihoo-shivamkumars** [comment]
yes it is working now
