### ISSUE TITLE
Help: Get all campaigns from all accounts for all customers.

### ISSUE THREAD

**Issue by alainjabmo** [BingAds/BingAds-Python-SDK#207]
Hello,
I try to retrieve all campaigns (not metrics) for all customers I manage.
Imagine, I have the following hierarchy:
![manageraccount-withhierarchy](https://user-images.githubusercontent.com/99672287/165555716-55ede02b-b463-4c53-ad45-fcebe65efbd1.png)
As "Manager Account L1", I would like to retrieve all campaigns for "Ad Account 1A" and "Ad Account 1B".

With GetAccountsInfo, I retrieve (in my case) 2 accounts. 
Running "GetCampaignsByAccountId" on those two accounts give me differents result. For one account, it's OK, for the second one, I got the following error:
```
Web service reported a SOAP processing fault using an unexpected HTTP status code 200. Reporting as an internal server error.
ErrorCode: CampaignServiceInvalidAccountId
Code: 1102
Details: None
Message: The account ID is invalid.
```
My both accounts are at the same level as "Ad Account 1A" and "Ad Account 1B".

Later, i want to be able to collect Campaigns informations for other levels. Is there a way of achieving that ?
Any idea ?

**Comment by rishaab** [comment]
Try adding the following lines at the top to see some logging information about your call to better see what your 'suds envelope' contains when sent to the API. 

```
import logging

logging.basicConfig(level=logging.INFO)
logging.getLogger('suds.client').setLevel(logging.DEBUG)
```

**Comment by qitia** [comment]
Could you please log out the requestid/trackingid with what @rishaab suggested and reach out suport team? sounds like your call with the "second account" has some authentication issue.
