### ISSUE TITLE
Please Publish Wheels 

### ISSUE THREAD

**Issue by atruslow** [BingAds/BingAds-Python-SDK#210]
Hi, 

I'm getting an error when I try to install this package via an sdist:

```
          history = f.read().replace('.. :changelog:', '')
        File "/Users/alexandertruslow/.pyenv/shims/python3.6/encodings/ascii.py", line 26, in decode
          return codecs.ascii_decode(input, self.errors)[0]
      UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 6791: ordinal not in range(128)
```
I was able to get around this by building a none-any wheel on a different machine, and then installing the wheel (thus not having to execute the `setup.py`).

Would you please consider publishing a wheel along with your `sidst`?

**Comment by atruslow** [comment]
> did you try to install with  pypi?

I did, and I was able to install it. Just wondering if your mind publishing a wheel in the future.

**Comment by qitia** [comment]
it is not on the radar right now.
