### ISSUE TITLE
How can I get MSCLKID of clicked ads?

### ISSUE THREAD

**Issue by GN-Jaswant** [BingAds/BingAds-Python-SDK#211]
Hi There

I'm raising this issue because I want to get MSCLKID. Please let me know is it possible to get MSCLKID along with other ads data or is there any data from I can access the click data.
As google ads have GCLID, so I'm supposing that bing ads also have something like that.

Thank you

**Comment by qitia** [comment]
I do not think the MSCLKID could be fetched from API/SDK. please reach out support team for help.

**Comment by qitia** [comment]
maybe you want document here: https://docs.microsoft.com/en-us/advertising/campaign-management-service/accountproperty?view=bingads-13.
