### ISSUE TITLE
GetAutoApplyOptInStatus not available in Ad Insight Service

### ISSUE THREAD

**Issue by zorion** [BingAds/BingAds-Python-SDK#212]
Hello.
I want to use GetAutoApplyOptInStatus as specified here:
https://docs.microsoft.com/en-us/advertising/ad-insight-service/getautoapplyoptinstatus?view=bingads-13#example

`response=adinsight_service.GetAutoApplyOptInStatus(RecommendationTypesInputs=RecommendationTypesInputs)`

But I receive `Method not found: 'AdInsightService.BasicHttpBinding_IAdInsightService.GetAutoApplyOptInStatus'`

If I check what I can use for Ad Insight Service it doesn't appear in the list (or maybe I'm doing something wrong).
So if I run:
`services = adinsight_service.soap_client.service._ServiceSelector__services`
`print([op.name for k, op in services[0].ports[0].binding.operations.items()])`

What I print doesn't contain the AutoApply operations (Get and/or Set).

`[GetBidOpportunities,
 GetBudgetOpportunities,
 GetKeywordOpportunities,
 GetEstimatedBidByKeywordIds,
 GetEstimatedPositionByKeywordIds,
 GetEstimatedBidByKeywords,
 GetEstimatedPositionByKeywords,
 GetBidLandscapeByAdGroupIds,
 GetBidLandscapeByKeywordIds,
 GetHistoricalKeywordPerformance,
 GetHistoricalSearchCount,
 GetKeywordCategories,
 GetKeywordDemographics,
 GetKeywordLocations,
 SuggestKeywordsForUrl,
 SuggestKeywordsFromExistingKeywords,
 GetAuctionInsightData,
 GetDomainCategories,
 PutMetricData,
 GetKeywordIdeaCategories,
 GetKeywordIdeas,
 GetKeywordTrafficEstimates]`

I have the most recent bingads  library installed from pip (Version: 13.0.13).
Is there something missing? Does it work for you? Thanks!

**Comment by zorion** [comment]
I think that GetAutoApplyOptInStatus is totally missing in `bingads/v13/proxies/production/adinsight_service.xml`.

I guess this should be recreated using `generate_all.bat` but I am not 100% sure and I don't have access to a Windows machine for testing it.

Please, could you have a look, fix it, and deploy a new version if I'm right? Thanks in advance!

**Comment by qitia** [comment]
This is new feature that is not supported from SDK yet. Please expect version 13.0.14 targeting early July 2022.
