### ISSUE TITLE
Server raised fault: Invalid client data. Check the SOAP fault details for more information

### ISSUE THREAD

**Issue by asrivastavsprighub** [BingAds/BingAds-Python-SDK#219]
Server raised fault: Invalid client data. Check the SOAP fault details for more information. TrackingId: ae2cf7a5-8ea4-4d15-99e6-89250223639e

**Comment by qitia** [comment]
as mentioned in [issue 190](https://github.com/BingAds/BingAds-Python-SDK/issues/190#issuecomment-1216301854), you should adopt MFA as per Microsoft Ads [request](https://docs.microsoft.com/en-us/advertising/guides/authentication-oauth-mfa?view=bingads-13).

**Comment by asrivastavsprighub** [comment]
thanks for response. we already implemented MFA. 5 days ago it was working but now it throws error

**Comment by qitia** [comment]
What I see from log is 
UserError...Code=OAuthTokenInvalid. Target=. Message=Authenticaton token contains invalid scope; expected=ads.manage or msads.manage; actual=ads.manage; ... 
I think this is due to invalid scope you are using.

**Comment by asrivastavsprighub** [comment]
TrackingId: 86c39098-51a4-4ff9-9c23-9619457f0e10. for this tracking id i used scope msads.manage.
but still getting same error

**Comment by qitia** [comment]
I see the same error. Could you please share your code piece?

**Comment by asrivastavsprighub** [comment]
#, 'oauth2_refresh_token': ''
oauth_token = OAuthTokens(access_token=@accesstoken,
                                  access_token_expires_in_seconds=3600,
                                  refresh_token=@refreshtoken)

authorization_data = AuthorizationData(
                        developer_token='@developertoken',
                        customer_id='@cid',
                        account_id='@cid', #i tried with cid & aid both
                        authentication=OAuthAuthorization(client_id=@clientid,
                                                            oauth_tokens= oauth_token
                                                          ),
        )

campaign_service = ServiceClient(
    service='CustomerManagementService', 
    version = 13,
    authorization_data=authorization_data, 
    environment = 'production',
)

# print(campaign_service.soap_client)

campaign_service.GetAccountsInfo(CustomerId=None,OnlyParentAccounts=False)

**Comment by qitia** [comment]
Thanks for sharing, I am most interested in how you get your accesstoken and refreshtoken. You need to give the the scope when you get refreshtoken first time right?

**Comment by asrivastavsprighub** [comment]
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=@clientid&scope=https://ads.microsoft.com/ads.manage offline_access&response_type=code&redirect_uri=https://sprighub.ai&state=ClientStateGoesHere
this url return code

https://login.microsoftonline.com/common/oauth2/v2.0/token 
-ContentType application/x-www-form-urlencoded 
-Method POST 
-Body "client_secret=$clientsecret&client_id=$clientId&scope=https://ads.microsoft.com/msads.manage offline_access&code=$code&grant_type=authorization_code&redirect_uri=https://sprighub.ai

this is first time token generation process

**Comment by asrivastavsprighub** [comment]
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=@clientid&scope=https://ads.microsoft.com/msads.manage offline_access&response_type=code&redirect_uri=[https://sprighub.ai&state=ClientStateGoesHere](https://sprighub.ai%26state%3Dclientstategoeshere/)

**Comment by qitia** [comment]
so you mean you already use **msads.manage** right? I cannot tell anything wrong with this. Did you see 2FA during the process?

**Comment by asrivastavsprighub** [comment]
Yes i am using msads.manage. it asking opt only when i am trying to authenticate that's it

**Comment by Ritik262** [comment]
Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: dd112067-7504-4d9b-a170-175dfaeb4b06.'
 

Please resolve this  issue

**Comment by Ritik262** [comment]
*** suds.WebFault: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 812a98df-6fad-494a-85c2-e78aa4ebf489.'
bulk_file_path = bulk_service_manager.download_file(download_parameters)
Please resolve this issue same issue again relase

**Comment by Zyuhang17** [comment]
Can I get some help as well:
Invalid client data. Check the SOAP fault details for more information. TrackingId: 21311e40-cc5b-47ec-8e10-b3d3a28c1353.

**Comment by qitia** [comment]
What I see from the log shows "The Account ID is invalid". Please make sure you are using correct accountId. You can find your account Id from web ui.

**Comment by elite-developer1055** [comment]
Hi @qitia 
I am getting this error:
suds.WebFault: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: a127babf-671e-4b36-a521-d928b100acea.'
Could you please check what is going on and what the solution is?
