### ISSUE TITLE
suds.WebFault: Server raised fault: 'The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter https://bingads.microsoft.com/AdInsight/v13:EntityIds. The InnerException message was 'Error in line 6 position 51. Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. '.  Please see InnerException for more details.'

### ISSUE THREAD

**Issue by Dorsaf-Sdiri** [BingAds/BingAds-Python-SDK#222]
Hello, 

I am requesting compaign data via bing api  using Python SDK, and this line of code throws a suds.WebFault error
get_keyword_ideas_response = adinsight_service.GetAuctionInsightData(EntityType ='Campaign',EntityIds =entityIds, SearchParameters=search_parameters). the EntityIds is np.array of accounts. and the search parameters are 
(ArrayOfSearchParameter){
   SearchParameter[] = 
      
      (DateRangeSearchParameter){
         EndDate = 
            (DayMonthAndYear){
               Day = 30
               Month = 8
               Year = 2022
            }
         StartDate = 
            (DayMonthAndYear){
               Day = 1
               Month = 8
               Year = 2022
            }
      },
      (AuctionSegmentSearchParameter){
         Segment = "Week"
      },,
 }
 Please help me fix this,

Thank you

**Comment by qitia** [comment]
the EntityIds parameter should be ns1:ArrayOflong, are you creating the right value for it?

https://learn.microsoft.com/en-us/advertising/ad-insight-service/getauctioninsightdata?view=bingads-13

GetAuctionInsightData(EntityType EntityType, ns1:ArrayOflong EntityIds, ArrayOfSearchParameter SearchParameters, AuctionInsightKpiAdditionalField ReturnAdditionalFields)

**Comment by Dorsaf-Sdiri** [comment]
I have attempt a list of ints, since in Python3 a long is natively an int. I have also converted it to numpy.array and array.array('l', entityIds) and the same exception remains, the response of soap variable is not rendering the data. Also it seems that there is a schema check via https://schemas.microsoft.com/2003/10/Serialization/Arrays in bulk_service.xml that is unavailble, do you think this is related ?
<img width="786" alt="xml_schema_check" src="https://user-images.githubusercontent.com/37803971/190969193-8c0712f4-f163-41c4-8344-f822ac4abd64.png">

**Comment by qitia** [comment]
you are trying adinsight api right? I do not think bulk_service will impact.

could you please show the full code piece you are using?

**Comment by Dorsaf-Sdiri** [comment]
Thank you so much for your responsiveness @qitia 
I am using this snippet of code along with the examples in the Github : Auth_hepler.py , campaignmanagment_example_helper.py , adInsight_example_helper and output_helper.py
```

import array as myarray
from AdInsightExampleHelper import *
from CompaignManagmeentExampleHelper import *
from AuthHelper import *
from OutputHelper import *

# You must provide credentials in AuthHelper.py.
LOCAL_FILE = "./auction-insight-june-2022.csv"


def main(authorization_data):
    #try:
    campaigns = campaign_service.GetCampaignsByAccountId(
        AccountId=authorization_data.account_id,
        CampaignType=['Search'])

    entityIds = []
    
    output_status_message("Campaigns:")
    for c in campaigns['Campaign']:
        if 'Concurrents' in c.Name:

            entityIds.append(c.Id)
            print(c.Name)
   
    
    entityIds = myarray.array('l', entityIds)

    search_parameters = adinsight_service.factory.create('ArrayOfSearchParameter')

    date_range_search_parameter = adinsight_service.factory.create('DateRangeSearchParameter')
    end_date = adinsight_service.factory.create('DayMonthAndYear')
    end_date.Day = 7
    end_date.Month = 8
    end_date.Year = 2022

    start_date = adinsight_service.factory.create('DayMonthAndYear')
    start_date.Day = 1
    start_date.Month = 8
    start_date.Year = 2022

    date_range_search_parameter.EndDate = end_date
    date_range_search_parameter.StartDate = start_date
   
    auctionSegmentSearchParameter = adinsight_service.factory.create('AuctionSegmentSearchParameter')
    auctionSegment = adinsight_service.factory.create('AuctionSegment')
    auctionSegment.Day;
    auctionSegmentSearchParameter.Segment = auctionSegment.Week
    #AuctionInsightKpiAdditionalField = adinsight_service.factory.create('AuctionInsightKpiAdditionalField')
    #returnAdditionalFields = AuctionInsightKpiAdditionalField.AbsoluteTopOfPageRate;

    EntityType = campaign_service.factory.create('EntityType')

    search_parameters.SearchParameter.append([date_range_search_parameter,auctionSegmentSearchParameter])
    print(search_parameters)
    get_keyword_ideas_response = adinsight_service.GetAuctionInsightData(EntityType ='Campaign', EntityIds = entityIds, SearchParameters=search_parameters )
    keyword_ideas = get_keyword_ideas_response

    if keyword_ideas is None:
        output_status_message("No keyword ideas are available for the search parameters.")
        sys.exit(0)

    #output_status_message("KeywordIdeas:")
    #output_array_of_keywordidea(keyword_ideas)

    #except WebFault as ex:
    #    output_webfault_errors(ex)
    #except Exception as ex:
    #    output_status_message(ex)


def download_file(response):
    CHUNK = 16 * 1024
    with open(LOCAL_FILE, 'wb') as f:
        while True:
            chunk = response.read(CHUNK)
            if not chunk: break
            f.write(chunk)
            f.flush()


# Main execution
if __name__ == '__main__':
    #output_status_message("Loading the web service client proxies...")

    authorization_data = AuthorizationData(
        account_id=None,
        customer_id=None,
        developer_token=DEVELOPER_TOKEN,
        authentication=None,
    )

    campaign_service = ServiceClient(
        service='CampaignManagementService',
        version=13,
        authorization_data=authorization_data,
        environment=ENVIRONMENT,
    )
    adinsight_service = ServiceClient(
        service='AdInsightService',
        version=13,
        authorization_data=authorization_data,
        environment=ENVIRONMENT,
    )

    auth = AuthHelper(authorization_data)
    auth()

    main(authorization_data)
```
If you would like to have a closer look into the full projet code, I have  invited you to a private repository

**Comment by akashdave-v** [comment]
Hey, I am also facing the same exact issue with AdInsightService API.

**Comment by qitia** [comment]
sorry missed replying to this thread. 

The issue I see in the sample code @Dorsaf-Sdiri share is - as I mentioned - usage of EntityIds. Could you please try below and let me know?
```
    entityIds = adinsight_service.factory.create('ns1:ArrayOflong')
    entityIds.long = [the entity ids]
```

@akashdave-v , let me know if this help as well, otherwise please share your code.

**Comment by akashdave-v** [comment]
Hey, @qitia It worked. Thank you very much.

**Comment by qitia** [comment]
Glad it worked. Close as of now.
