### ISSUE TITLE
Server raised fault: Invalid client data. Check the SOAP fault details for more information 

### ISSUE THREAD

**Issue by clemiblac** [BingAds/BingAds-Python-SDK#225]
Hello, I have been getting this error since Sunday and I am unable to view the SOAP fault details
 
WebFault: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: dd29c4d9-eeac-43ec-bc99-a0dbd665edda.'

I see similar questions from a few months ago but suggestions did not change anything. Could you kindly assist?

**Comment by qitia** [comment]
Can you repro this? We did have a regression last week at service side, but it already got fixed. Please let me know if you can still repro it.

BTW, which version of SDK are you using? the latest version is 13.0.14. I would like to suggest you upgrade SDK version to latest one.

**Comment by clemiblac** [comment]
Hello Quitia, I am guessing the regression was the issue because it works now. I had this issue from 10/23 through 10/25. I started exploring alternatives outside of the API after that so I may not have seen the fix. Thank you for your help!
