### ISSUE TITLE
Performance report request does not include campaign with zero data

### ISSUE THREAD

**Issue by dataSem** [BingAds/BingAds-Python-SDK#227]
Hi, I'm currently using the following example to download a campaign report:

https://learn.microsoft.com/en-us/advertising/guides/code-example-report-requests?view=bingads-13

The issue I'm facing is the report returning only account with some data (clicks, imp, conv, etc) but the ones with no data are not returning information. 

Reading the docs I haven't been able to find how can I get all the campaigns regardless if they have data or not.

```
    campaign_performance_report_request=get_campaign_performance_report_request(
        account_id=account_id,
        aggregation=aggregation,
        exclude_column_headers=exclude_column_headers,
        exclude_report_footer=exclude_report_footer,
        exclude_report_header=exclude_report_header,
        report_file_format=REPORT_FILE_FORMAT,
        return_only_complete_data=return_only_complete_data,
        time=time)
```

Any ideas how can I get all the campaigns under the account. 

Thanks

**Comment by qitia** [comment]
hi there, per the feature owner, this is by design. if you would like to fetch data of all campaigns, you maybe want to try bulkdownload.
