### ISSUE TITLE
Remote end closed connection without response

### ISSUE THREAD

**Issue by Myrzaly** [BingAds/BingAds-Python-SDK#228]
Hi ! 

I am trying to get Bing Ads metadata, but receiving "Remote end closed connection without response" error. My authentication is successful, and I have refreshed token, but still receive the same error. 
Following are the screencaps for your reference. 

![8fj4SovQ87](https://user-images.githubusercontent.com/120097418/206426758-3891bed2-f80f-4a45-b19b-7dbd711d2fc7.png)

![pycharm64_OJeIdEJepD](https://user-images.githubusercontent.com/120097418/206426857-b72daf43-e568-4577-a2f8-6ef7f8fe2d15.png)

Can you please help to resolve this issue ? Thanks !

**Comment by qitia** [comment]
can you show how to repro this? do you have tracking id /request id? or any more info for us to debug into?
