### ISSUE TITLE
Server raised fault: Invalid client data

### ISSUE THREAD

**Issue by abmounir** [BingAds/BingAds-Python-SDK#231]
Hi,
i am trying to get user info (like user id ) using ``ServiceClient``. I have successfully authenticated and i can even display access and refresh tokens.

Here is my code:
```python
customer_service=ServiceClient(
        service='CustomerManagementService', 
        version=13,
        authorization_data=authorization_data, 
        environment='Sandbox',
    )

get_user_response=customer_service.GetUser(
            UserId=None
        )
```

But i am getting this error: 
```raise WebFault(fault, replyroot)
suds.WebFault: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId:```

**Comment by qitia** [comment]
so do you have the trackingid?

**Comment by abmounir** [comment]
@qitia Here 's my trackingid: 324a7c6a-1d9a-4d12-b6be-aa274dbfd299

**Comment by qitia** [comment]
Checked the service log and seems you are using sandbox env, and the error message shows that your passing invalid OAuthToken.

**Comment by Navneetk-bst** [comment]
@qitia I am facing the same issue. **Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 379c4c21-3403-48f4-bcf5-564799e8c7a3.**' Can you please check from this tracking id what is the possible reason.

**Comment by qitia** [comment]
and you should be provide invalide auth token as well: Sender fault: OAuthTokenInvalid: Authentication token type is invalid.
