### ISSUE TITLE
[QUESTION] Release 13.0.15: what were the recent interface changes?

### ISSUE THREAD

**Issue by yuzeh** [BingAds/BingAds-Python-SDK#232]
Hi team, I'm not sure where this question is best asked, so I hope you don't mind if I open an issue here.

We're debugging what we think may be an issue with the Bing Ads API, and I was trying to look for a log of recent changes.

The release notes for [bingads Python library version v13.0.15](https://github.com/BingAds/BingAds-Python-SDK/releases/tag/v13.0.15) say:

> Update Bing Ads API Version 13 service proxies to reflect recent interface changes. For details please see the Bing Ads API Release Notes: https://docs.microsoft.com/en-us/bingads/guides/release-notes.

However, on following the release notes, there doesn't seem to be anything that indicates a change was made since November 2021 (except perhaps a notice about MFA stuff on June 1, 2022).

With that in mind, I have two questions:
1. What were the recent interface changes that were made that are reflected in v13.0.15?
2. Is there a separate forum where I can get support with API-related (but not python library-related) issues?

Many thanks!

**Comment by qitia** [comment]
hi yuzeh, the Release Notes: https://docs.microsoft.com/en-us/bingads/guides/release-notes may be kinds of out of update. For this library, we update the content in https://github.com/BingAds/BingAds-Python-SDK/tree/main/bingads/v13/proxies to reflect the latest svc in each version.
