### ISSUE TITLE
Reported security vulnerability in dependency "future".

### ISSUE THREAD

**Issue by steve-mavens** [BingAds/BingAds-Python-SDK#233]
Dependabot has just thrown this at my bingads code: https://github.com/advisories/GHSA-v3c5-jqr6-7qm8

On a quick search of the head of your main branch, it looks to me as though the only use of `future` is several cases of `from future.utils import with_metaclass`. That's thoroughly harmless, and I'm confident guessing that it's not subject to a vulnerability in cookie-handling code! Nothing else in my application uses `future`, so I can dismiss my dependabot alert.

Still, it might be helpful to your users if you cut the dependency on `future` by specifying your metaclasses in Python 3 syntax (judging by your trove classifiers, you no longer support Python 2 anyway). I've never used `with_metaclass` before, but I believe that for example: `class _BulkEntityIdentifier(with_metaclass(ABCMeta, _BulkObject)):` translates to `class _BulkEntityIdentifier(_BulkObject, metaclass=ABCMeta):`.

The last release of `future` was 3 years ago, so I don't know whether that's still maintained. Perhaps it will respond to the advisory with a fix, in which case there's no need to change anything, but it doesn't look promising: https://github.com/PythonCharmers/python-future/pull/610

Even if you don't plan to change anything, I propose that this ticket might help anyone else who ends up here in the next few days because they got the same dependabot alert. Saves them doing the same check of the code :-)

If you are changing it, then while you're in there, there are some `from __future__ import print_function` and similar that are no longer needed provided you don't support Python 2.

**Comment by wpwood** [comment]
We're running into this issue, too. According to https://github.com/PythonCharmers/python-future/issues/612#issuecomment-1371996864, it doesn't look like future is going to be updated. They suggest removing future from usage, given that "It is supposed to help moving from Python 2 to 3. Python 2 has been dead for a long time."

**Comment by Kache** [comment]
Looks like [v13.0.15 removes support for Python 2](https://github.com/BingAds/BingAds-Python-SDK/commit/eae386006f597f9dff070c333e496225547a5917#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L58-L60), but it missed removing the `future` dep

**Comment by steve-mavens** [comment]
v0.18.3 of `future` contains the fix to the cookie code: https://github.com/PythonCharmers/python-future/compare/v0.18.2...v0.18.3

**Comment by qitia** [comment]
yes we will remove six/future in vNext.
