### ISSUE TITLE
suds.WebFault: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId:

### ISSUE THREAD

**Issue by Zyuhang17** [BingAds/BingAds-Python-SDK#239]
Can you help me with this please? I am trying to connect to the API

**Comment by qitia** [comment]
Message: The account ID is invalid

**Comment by menporulporiayalan** [comment]
@qitia  I am having a similar issue.  I can able to get the campaigns and Adgroups from the account. But I am receiving this error when I tried to submit "GenerateReport".

**Comment by qitia** [comment]
I can not help anything without detail @menporulporiayalan. Can you please share trackingid/requestid, times when you made the call and so on?

**Comment by menporulporiayalan** [comment]
@qitia  Sorry, I found out the issue.  I was passing the account ID below 

`scope.AccountIds=account_id`

Instead of 

`scope.AccountIds={'long': [account_id] }`

which caused the error.   Now its working fine

**Comment by qitia** [comment]
@Zyuhang17, is your issue resolved?

**Comment by Zyuhang17** [comment]
@qitia Thank you for the response. Unfortunately, the problem is still not solved. I tried to use account_id as the form {'long': [account_id] }, the error tracking id is:
suds.WebFault: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 9d851d96-ad7d-4f3c-b8ac-0a65d1833300.'

May I ask: 
1. We are currently using the account ID from the UI. But is the account ID all numbers or it is letters+numbers
2. It looks like I can get the User ID response when passing through XML UserID request, but when i pass in the account ID, program fails using python SDK.
3. are we passing in the master customer ID for each API call or we should pass in client specific Customer IDs

Thank you!

**Comment by qitia** [comment]
it is still the "AccountId invalid" error. AccountId is all numbers.
![image](https://user-images.githubusercontent.com/29188289/234151183-3abf4446-40b6-4ecc-8eb9-3bea1b79a577.png)

**Comment by Zyuhang17** [comment]
@qitia,
Thanks for the help. Issue has been resolved. 
Can I ask a different question please:
**- How long does the refresh token last before we need to rotate it out? **

**Comment by qitia** [comment]
around 90 days. but there is no guarantee. please open another issue as necessary thus we can track easier.

**Comment by Zyuhang17** [comment]
thanks,
Could you please help me check this ID?
suds.WebFault: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: ef67a92f-529e-448b-9b24-daa3dbf2ba94.'
