### ISSUE TITLE
campaign_service.factory.create('ns3:ArrayOfstring') Error

### ISSUE THREAD

**Issue by Zyuhang17** [BingAds/BingAds-Python-SDK#243]
@qitia 
hello can I get some help here on the ("Type not found: 'ns3:ArrayOfstring'") issue?

I followed the SDK instruction and here is the error message. It looks like something is missing from the suds packages when I try to execute this line: final_urls = campaign_service.factory.create('ns3:ArrayOfstring')

Thanks!

**Comment by qitia** [comment]
```
>>> from suds.client import Client
>>> c = Client('https://campaign.api.bingads.microsoft.com/Api/Advertiser/CampaignManagement/v13/CampaignManagementService.svc?wsdl')
...
ns4:ArrayOfstring
...
```

**Comment by Zyuhang17** [comment]
thanks
