### ISSUE TITLE
The image ad extension's DisplayText is too long.

### ISSUE THREAD

**Issue by OArapoglu** [BingAds/BingAds-Python-SDK#247]
In the official documentation, the max length of display text of image extensions is 100 and it is optional. But, when I send an image ad extension without display_text, it raises it can not be null. If I set the display_text within 100 chars, it raises 'The image ad extension's DisplayText is too long.'. However, if I set it within at most 35 chars, it works properly. Could you check your official documentation about it and give me feedback about this issue.
The image ad extension's DisplayText is too long.
Please check below link for display text.
https://learn.microsoft.com/en-us/advertising/campaign-management-service/imageadextension?view=bingads-13
Thank you

**Comment by rgaritta** [comment]
Hi @OArapoglu, 

Thanks for pointing this out. I have updated the documentation: https://learn.microsoft.com/en-us/advertising/campaign-management-service/imageadextension?view=bingads-13.
