### ISSUE TITLE
Cannot fetch details for Audience campaign

### ISSUE THREAD

**Issue by sfontana** [BingAds/BingAds-Python-SDK#248]
### Problem
I'm unable to get details for an Audience campaign with ID `482757685`:

```python
campaigns = campaign_service.GetCampaignsByIds(
    AccountId=151003430, CampaignIds={'long': [482757685]}, CampaignType=['Audience'],
)

>>> campaigns
(reply){
   Campaigns = 
      (ArrayOfCampaign){
         Campaign[] = <empty>
      }
   PartialErrors = ""
 }
```

I'm attaching the [full log of the request](https://github.com/BingAds/BingAds-Python-SDK/files/11771571/request.log).

This is a problem because in order to get campaign performance filtered by campaign name, we first need to fetch all the campaigns. On top of that, this is a silent error, so users won't notice something is wrong until they double-check the numbers in the UI.

#### Additional notes
 -  Audience campaigns are also omitted when using `GetCampaignsByAccountId`:
 
```python
   result = campaign_service.GetCampaignsByAccountId(
            AccountId=151003430, CampaignType=['Audience DynamicSearchAds Search Shopping']
        )
```
 - If I specify a non-existent ID, the expected error gets raised. This makes me think that the backend is aware of the campaign's existence, but it just cannot return its details for some reason, maybe something is wrong with the XML definition?
 - I'm able to fetch search campaigns using the same method.
 - I've tried versions `13.0.14`, `13.0.15` and `13.0.16` of this SDK.
 - The campaign had 170K+ impressions for the period 2023.01.01-2023.06.13.
 <img width="442" alt="image" src="https://github.com/BingAds/BingAds-Python-SDK/assets/6084566/53d68ac9-5954-4c3b-8c04-0a5145a9bc00">

**Comment by sfontana** [comment]
@qitia @rgaritta tagging you directly in case you didn't see this, thanks in advance for the help :)

**Comment by qitia** [comment]
hi @sfontana, checked your campaign, its biddingscheme is ManualCPM, per the [document](https://learn.microsoft.com/en-us/advertising/campaign-management-service/campaignadditionalfield?view=bingads-13). You need to set the CpvCpmBiddingScheme in the CampaignAdditionalField. Try below and let me know
```
campaigns = campaign_service.GetCampaignsByIds(
    AccountId=151003430, CampaignIds={'long': [482757685]}, CampaignType=['Audience'], ReturnAdditionalFields=['CpvCpmBiddingScheme'])
```

**Comment by sfontana** [comment]
@qitia that works, thank you so much!

I had only checked [`GetCampaignsByIds` document](https://learn.microsoft.com/en-us/advertising/campaign-management-service/getcampaignsbyids?view=bingads-13) and didn't think to check the `ReturnAdditionalFields` page.
