### ISSUE TITLE
reporting_service_manager not working

### ISSUE THREAD

**Issue by j450h1** [BingAds/BingAds-Python-SDK#25]
Ultimately, I want to download a report using:

    reporting_download_operation = reporting_service_manager.submit_download(report_request)

This is the error message I get when executing:

        reporting_service_manager=ReportingServiceManager(
           authorization_data=authorization_data, 
           poll_interval_in_milliseconds=5000, 
          environment=ENVIRONMENT,
       )

ValueError: Cannot find version: [v10] service: [ReportingService] under environment: [production].             Please notice that campaign management, bulk, ad intelligence and optimizer services were deprecated in v9

**Comment by imagineful** [comment]
Hi, Thanks for your feedback. This is a bug. Reporting service is only supported in v9, while currently ReportingServiceManager could not set the version from outside, could you try below as a workaround:
1. bingads\reporting\reporting_service_manager.py , line 39, add version=9:
self._service_client = ServiceClient('ReportingService', authorization_data, environment, version=9, **suds_options)
2. bingads\reporting\reporting_operation.py, line 56, add version=9:
self._service_client = ServiceClient('ReportingService', authorization_data, environment, version=9, **suds_options)

We will provide the fix in the next release soon.
Thanks.

**Comment by imagineful** [comment]
Released hotfix version 10.4.6, could you please upgrade to this version? this issue should be fixed.
Thanks.

**Comment by j450h1** [comment]
Thanks, the workaround "worked", but I will just go ahead and update as well.

**Comment by j450h1** [comment]
Update works well too. Thanks again!
