### ISSUE TITLE
adinsight_service.GetRecommendations returns nothing

### ISSUE THREAD

**Issue by puerile22** [BingAds/BingAds-Python-SDK#256]
Here's my request tracking id 7357b384-8929-420e-8a7b-d0a533970519

I can see more than 300 ads recommendations in microsoft ads UI interface, but when I try to get it through the api it just returns nothing. I tried both setting campaign ID and ad group ID and left them empty but I still didn't get anything.

**Comment by MrOllzzor** [comment]
According to the documentation only ResponsiveSearchAdsOpportunity is supported..

In the request you have to specify RecommendationType.
RecommendationType | The identifier of the recommendation type that you want to get. Currently only ResponsiveSearchAdsOpportunity is supported.This element can't be nil or empty. One recommendation type per request, e.g., ResponsiveSearchAdsOpportunity.

Read more at:
https://learn.microsoft.com/en-us/advertising/ad-insight-service/getrecommendations?view=bingads-13

**Comment by qitia** [comment]
per investigation from backend, we did not find RSA recommendation for account id: 145xxxxx4, please reach out to Microsoft Advertising Technical Support <adsupport@microsoft.com> for help.
