### ISSUE TITLE
Web service reported a SOAP processing fault using an unexpected HTTP status code 200. Reporting as an internal server error.

### ISSUE THREAD

**Issue by hassan1731996** [BingAds/BingAds-Python-SDK#259]
I'm facing the same issue atm
suds.WebFault: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: 0b0f43fa-1b5f-4a14-9946-960d29c40966.'
tracking id also added here. please help me @qitia

**Comment by qitia** [comment]
I see this from the log: User chose organization authentication type but only have personal account.

Please check your settings and reach out to "adsupport@microsoft.com" for more help if you can not fix it.

**Comment by hassan1731996** [comment]
One more question @qitia , is there any way where i could put this TrackingId & get full information why its failing ?
i dont want to bother you every time :)

**Comment by qitia** [comment]
this is internal trackingid, please reach out to support team if you have any login/auth issue, providing them the trackingid and they can help.
