### ISSUE TITLE
Issue with SOAP Processing Fault and Unexpected HTTP Status Code 200 in CampaignManagementService

### ISSUE THREAD

**Issue by ronniejoshua** [BingAds/BingAds-Python-SDK#266]
Subject: Issue with SOAP Processing Fault and Unexpected HTTP Status Code 200 in CampaignManagementService

Description:
I am encountering an issue with the CampaignManagementService while attempting to retrieve campaigns using the GetCampaignsByAccountId method. The error message indicates a SOAP processing fault with an unexpected HTTP status code 200. The specific error message is as follows:

`Web service reported a SOAP processing fault using an unexpected HTTP status code 200. Reporting as an internal server error. Error occurred while processing account ID 18XXXXX6: Server raised fault: 'Invalid client data. Check the SOAP fault details for more information. TrackingId: b794afa1-5323-437d-93f3-524c1eae3f83.'
`

`
campaignmanagement_service = ServiceClient(
    'CampaignManagementService',
    version=13,
    authorization_data=authorization_data,
    environment=ENVIRONMENT
)
response = campaignmanagement_service.GetCampaignsByAccountId(AccountId=18XXXXX6)
`

Steps to Reproduce:

Initialize ServiceClient with the appropriate parameters.
Call GetCampaignsByAccountId method with a valid account ID.
Expected Behavior:
The method should return the campaigns associated with the specified account ID without any errors.

Actual Behavior:
The request results in a SOAP processing fault with an unexpected HTTP status code 200, and the error message indicates an issue with client data.

Additional Information:

Account ID: 18XXXXX6
Tracking ID: b794afa1-5323-437d-93f3-524c1eae3f83

**Comment by qitia** [comment]
what I see from log is "Customer ID is invalid". if you still see this issue, please reach out to support team for help. Normally we should raise question here on how to use this library.

**Comment by qitia** [comment]
adsupport@microsoft.com
