### ISSUE TITLE
NameError: name 'TargetImpressionShare' is not defined

### ISSUE THREAD

**Issue by SiebertLooijeAtBillyGrace** [BingAds/BingAds-Python-SDK#295]
The TargetImpressionShare is not defined in the bulk operation:

![image](https://github.com/user-attachments/assets/1dcd2b1f-45d1-407c-8ff0-dcf37015a780)

The object 'TargetImpressionShare' is not defined in the bingads.v13.internal.extensions.py

https://github.com/BingAds/BingAds-Python-SDK/blob/v13.0.21.1/bingads/v13/internal/extensions.py

I think: row_values[_StringTable.BidStrategyTargetImpressionShare] = TargetImpressionShare(entity.BiddingScheme.TargetImpressionShare), should be:

row_values[_StringTable.BidStrategyTargetImpressionShare] = bulk_str(entity.BiddingScheme.TargetImpressionShare)

**Comment by xinyuwen2** [comment]
Thank you! This fix is available in version 13.0.21.2
