### ISSUE TITLE
authorization.py - line 400

### ISSUE THREAD

**Issue by VerdigrisReader** [BingAds/BingAds-Python-SDK#36]
oauth_web_auth_code_grant.request_oauth_tokens_by_response_uri sends out a the client secret with the post request, causing the following error:

OAuthTokenRequestException: error_code: invalid_request, error_description: Public clients can't send a client secret.

Solution - remove the client_secret parameter from this request at authorization.py:400

**Comment by imagineful** [comment]
Thanks @VerdigrisReader 
Verified this issue, we will fix it in next release. as the workaround, we can either remove the client_secret parameter as you suggested, or we can just set this client_secret to None, thus this parameter will be removed from the request.

**Comment by imagineful** [comment]
Hi, @VerdigrisReader could you please verify if this issue still exist? I just noticed that something changed from live.com, the client secret is required as I tested from my side.

**Comment by imagineful** [comment]
close issue. if anything else please feel free to reopen it or open a new issue. thanks.
