### ISSUE TITLE
pip install bingads gettting error

### ISSUE THREAD

**Issue by Alonreznik** [BingAds/BingAds-Python-SDK#41]
Trying to install bingads with pip install and getting that error:

> C:\Users\a>pip install --upgrade bingads
> 
> Downloading/unpacking bingads
>   Cannot fetch index base URL https://pypi.python.org/simple/
>   Could not find any downloads that satisfy the requirement bingads
> Cleaning up...
> No distributions at all found for bingads
> Storing debug log for failure in C:\Users\a\pip\pip.log

Please fix

Thanks!

**Comment by imagineful** [comment]
Hi, Alonreznik, thanks for your feedback, I have tried on windows system, and I can upgrade bingads python SDK from version 10.4.8 to 10.4.10.
Which pip version are you using?

Thanks

**Comment by eric-urban** [comment]
No repro
