### ISSUE TITLE
Missing Support for Reporting Service v11 (and Report Request Parameter ExcludeReportHeader)

### ISSUE THREAD

**Issue by RogerWebb** [BingAds/BingAds-Python-SDK#54]
I attempted to use the ExcludeReportHeader parameter of the Report Request object as described here:
https://msdn.microsoft.com/en-us/library/bing-ads-reporting-bing-ads-reportrequest.aspx

When I attempt to use this via something like "report_request.ExcludeReportHeader = True" an Exception (TypeNotFound). 

Digging in, it seems the Reporting Service is limited to version 10 and this feature, according to the article, is only available in v11.  If I attempt to set the version to 11, I get the following error:

"ValueError: version error: [11] is not supported."

This limit appears to be hard-coded in bingads/service_client.py in the method "_format_version"

**Comment by iamdoron** [comment]
Hi,

you have to specify the version when you create the reporting service:
```python
     reporting_service = ServiceClient(
          'ReportingService',
          authorization_data=authorization_data,
          version=11
      )
```

**Comment by eric-urban** [comment]
@iamdoron is correct. Thanks!
