### ISSUE TITLE
looking for API to upload offline conversions

### ISSUE THREAD

**Issue by jyoo23** [BingAds/BingAds-Python-SDK#58]
I'm looking for the API to upload offline conversions.
I see conversion goal API but not for conversion upload.
In this guide below only explain uploading files manually.
https://help.bingads.microsoft.com/#apex/3/en/56852/-1

Is there an API that we can do this automatically?

**Comment by qingjuntian** [comment]
Is CampaignManagementService.ApplyOfflineConversions what you r looking for?
