### ISSUE TITLE
references to keyword.Amount throws error

### ISSUE THREAD

**Issue by alexcurrysvg** [BingAds/BingAds-Python-SDK#60]
For example: 
https://github.com/BingAds/BingAds-Python-SDK/blob/master/examples/BingAdsPythonConsoleExamples/BingAdsPythonConsoleExamples/v11/output_helper.py 

**def output_keyword(keyword):
       if keyword is not None:
             output_status_message("Bid.Amount: {0}".format(
                 keyword.Amount if keyword.Bid is not None else None)
               )**

keyword object appears to have the structure keyword.Bid.Amount not keyword.Amount

**Comment by eric-urban** [comment]
@alexcurrysvg sorry for the delay! This is updated. Thank you.
