### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by pocin** [BingAds/BingAds-Python-SDK#66]
I am having some memory issues when downloading reports. I checked a large portion of the source code and it seems that iterators and streaming is used all over the place. However this line bogs me - https://github.com/BingAds/BingAds-Python-SDK/blob/67c00e9e14b6565c5f1e6f3f3c2fbd6cabd3f5b0/bingads/reporting/reporting_operation.py#L128 doesn't it result in reading the whole file in memory?

and shouldn't it be  something along these lines?
```python
                with contextlib.closing(zipfile.ZipFile(zip_file_path)) as compressed:
                    first = compressed.namelist()[0]
                    with open(result_file_path, 'wb') as f, compressed.open(first, 'r') as c:
                        for line in c:
                            f.write(c)
```

**Comment by pocin** [comment]
I actually made some quick and dirty benchmarks and this would be best to use:

```python
import shutil
                with contextlib.closing(zipfile.ZipFile(zip_file_path)) as compressed:
                    first = compressed.namelist()[0]
                    with open(result_file_path, 'wb') as f, compressed.open(first, 'r') as c:
                        shutil.copyfileobj(c, f)
```

this consumes almost zero memory

**Comment by eric-urban** [comment]
@pocin we updated [bulk_operation](https://github.com/BingAds/BingAds-Python-SDK/blob/master/bingads/v11/bulk/bulk_operation.py#L123) and [reporting_operation](https://github.com/BingAds/BingAds-Python-SDK/blob/master/bingads/v11/reporting/reporting_operation.py#L129).
