### ISSUE TITLE
Report Request does not download result file

### ISSUE THREAD

**Issue by CurtisGreenland** [BingAds/BingAds-Python-SDK#71]
I successfully started using the python SDK, using it to pull performance reports using the example code provided here on GitHub. I am using the report_request.py example.  I had been using it daily since the beginning of December with no issues.  However, on January 1, everything stopped working with no changes to the code, and I have not been successful since then.  

It appears to get through the creation of the report request, but seems to fail on the submit and download,

The output from running the report_requests.py:
runfile('Y:/report_requests.py', wdir='Y:/')
Python loads the web service proxies at runtime, so you will observe a performance delay between program launch and main execution...

Awaiting Background Completion . . .
Download result file: None

Awaiting Submit and Download . . .
Download result file: None

Awaiting Download Results . . .
Download result file: None
Status: Success

Program execution completed

**Comment by sflynn-mf** [comment]
I am having the exact same issue I would love to see this resolved!

**Comment by qingjuntian** [comment]
Could you please provide more detail info? Do you have trackingID or requestID? Or account info?

**Comment by eric-urban** [comment]
@CurtisGreenland and @sflynn-mf are you running this in sandbox or production? If there is no data for the time period specified in the request, then by design the service return success without any download URL. 

It would help to understand what report type, date range, report columns, etc you are requesting. You can turn on [logging](https://github.com/BingAds/BingAds-Python-SDK/blob/master/examples/BingAdsPythonConsoleExamples/BingAdsPythonConsoleExamples/v11/auth_helper.py#L37) to capture the SOAP request and response. The trace will include TrackingId as @qingjuntian requested. Please don't share credentials or account IDs here in public view. If we need such details to continue the investigation then we will suggest that you [contact support](https://advertise.bingads.microsoft.com/en-us/bing-ads-support). 

```python
import logging
logging.basicConfig(level=logging.INFO)
logging.getLogger('suds.client').setLevel(logging.DEBUG)
logging.getLogger('suds.transport.http').setLevel(logging.DEBUG)
```

BTW if you are indeed running the sample daily in production please note that only one of the "options" is needed. You can save time and resources commenting out or removing the other options e.g., just use [Option A](https://github.com/BingAds/BingAds-Python-SDK/blob/master/examples/BingAdsPythonConsoleExamples/BingAdsPythonConsoleExamples/v11/report_requests.py#L35) and remove B and C.

**Comment by sflynn-mf** [comment]
I am running in production as I am using OAuth to authenticate and I think I remember seeing somewhere sandbox mode wouldn't play nice with OAuth. You may be on to something with the date however give me a moment to check that out.

I did not change anything inside the file as far as date range, report columns, sort etc...  The report type is set to what's returned by get_keyword_performance_report().

SOAP Messages: 
 
Here is the request with time stamp 2018-01-15 16:24:44.351673.
 
<?xml version="1.0" encoding="UTF-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Header>
      <h:TrackingId xmlns:h="https://bingads.microsoft.com/Reporting/v11">1c67ca0e-8846-4071-afb0-06e1e9f441a3</h:TrackingId>
   </s:Header>
   <s:Body>
      <SubmitGenerateReportResponse xmlns="https://bingads.microsoft.com/Reporting/v11">
         <ReportRequestId>30000001087803661</ReportRequestId>
      </SubmitGenerateReportResponse>
   </s:Body>
</s:Envelope>
 
 
Here is the response.
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Header>
      <h:TrackingId xmlns:h="https://bingads.microsoft.com/Reporting/v11">1be17748-56c6-46f9-a2df-676d93d91df9</h:TrackingId>
   </s:Header>
   <s:Body>
      <PollGenerateReportResponse xmlns="https://bingads.microsoft.com/Reporting/v11">
         <ReportRequestStatus xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
            <ReportDownloadUrl i:nil="true" />
            <Status>Success</Status>
         </ReportRequestStatus>
      </PollGenerateReportResponse>
   </s:Body>
</s:Envelope>
 
What’s strange to me is that the status of THIS response is Success (the last two or three PollGenerateReportResponse's came back as pending) so that must mean the report has finished downloading, but the ReportDownloadUrl is always None when I check it in my program, and no files are ever downloaded to my machine.

I just downloaded the SDK yesterday so my apologies if I'm missing something obvious!

**Comment by sflynn-mf** [comment]
Thank you so much @eric-urban. I changed the date range and it started working instantly.

Thank you so much for your time! I will consult occam's razor next time.

**Comment by CurtisGreenland** [comment]
@eric-urban 
I am in production. And there should be data for yesterday. If I run a keyword performance report in the Bing Ads UI, results come back.

Here is the output of the logging (I have X'd over all account ID's and developer token):

`<suds.sax.document.Document object at 0x000000000F62FA90>
DEBUG:suds.client:headers = {'Content-Type': 'text/xml; charset=utf-8', 'SOAPAction': b'"SubmitGenerateReport"', 'User-Agent': 'BingAdsSDKPython 11.5.7 (3, 6, 3)'}
DEBUG:suds.transport.http:sending:
URL: https://reporting.api.bingads.microsoft.com/Api/Advertiser/Reporting/V11/ReportingService.svc
HEADERS: {'Content-Type': 'text/xml; charset=utf-8', 'SOAPAction': b'"SubmitGenerateReport"', 'User-Agent': 'BingAdsSDKPython 11.5.7 (3, 6, 3)', 'Content-type': 'text/xml; charset=utf-8', 'Soapaction': b'"SubmitGenerateReport"', 'User-agent': 'BingAdsSDKPython 11.5.7 (3, 6, 3)'}
MESSAGE:
b'<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="https://bingads.microsoft.com/Reporting/v11" xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://bingads.microsoft.com/Reporting/v11" xmlns:ns2="http://schemas.microsoft.com/2003/10/Serialization/Arrays"><SOAP-ENV:Header><tns:AuthenticationToken>EwAIA3hlBAAUgdQjroa0siFqrG5FNB4+4uqtlVkAASzJRNx5u6n2+RqcMFVDyoqWs8MceqCtfkS3vabMx+TAOTu0aoG71hGkdcMWcGw/jImoUjxNe6iLI/HqL+Iflo5RhnMZtB1b/drmOw6RCotV8Qv7QfpfZohnPg4X5soCZVwGncPdeKBdDwrpJ8RATd1xdY4aj/Kt+tPjJFHB/NJ+YxCjJrj2XC7rpkGrpyvTyeHRYsxFjrpxfIxaoO7y/YrI22DAiFe1n4NeQ+LI5MygU1BDBBr/cdSxINspeELR6MXbD8HGkllOXaSackBVIgA2jEGceX8d8yhV3lKkTekNpW7/eQ5ZpHbjvOJxz9cqAOFq8lNj5V17UMLkmnrfe40DZgAACNrifECD0znp2AEltVuI44xFGUMxYPpe75cUYwweDXIpwjaacNY6vVex4mwfW4YCt+wbm5HvJxRgSCfX0mg9uhcinGPdZ39MxNZ2MbvN0aU+3FMdZ++L5XNu613y/IeabUFZDUlgVQN4CDfZzDneqgcpmahZueD0TPJVl+X+2pPzTw6Ua/X5OvlgEyid2UmEbc2HRDDBkRYLtr0RnqSGYTmcJe8nlrUjyus9Cl9LopDgyXDI/Rgw5vcvUUIFJLIWjhYgcCgKsk17y9dcYYegQLlo380LgW/uMiMpVjHACg6SDCANhr35mJy3J8y/vd4xFjqTWx2UQCUe6Ci1RrySEj8filCxtarLVLGfTduRXpSLZjjDFTAigmf0nMmIJFI3TAvl2xSvYoQNL6+ZvTKWAY76FZ6Dz0ijHUXcg+Yl6UN1C6Jp5X5UiZy1ppemyA4kJNFmvxT9R/5fRCht/1turXLKFP9pBNSJ4hr6eTIAYDyoKhsmjHR7kdIOpmJaTn1uaJUtmej30hrj7gJVKKBf8onds06epUS+qRf2zIFC6xpPcavvYENaYYYXBOjaANlSr3LqM78o35RZ+JXY7Dy720hyqZzO9sItNEqCxkECUGcElstuLd1NCCs6QH2+w4Bk8AD+IwI=</tns:AuthenticationToken><tns:CustomerAccountId>XXXXXXX</tns:CustomerAccountId><tns:CustomerId>XXXXX</tns:CustomerId><tns:DeveloperToken>XXXXXXXXXX</tns:DeveloperToken></SOAP-ENV:Header><ns0:Body><ns1:SubmitGenerateReportRequest><ns1:ReportRequest xsi:type="ns1:KeywordPerformanceReportRequest"><ns1:Format>Csv</ns1:Format><ns1:Language>English</ns1:Language><ns1:ReportName>My Keyword Performance Report</ns1:ReportName><ns1:ReturnOnlyCompleteData>false</ns1:ReturnOnlyCompleteData><ns1:Aggregation>Daily</ns1:Aggregation><ns1:Columns><ns1:KeywordPerformanceReportColumn>TimePeriod</ns1:KeywordPerformanceReportColumn><ns1:KeywordPerformanceReportColumn>AccountId</ns1:KeywordPerformanceReportColumn><ns1:KeywordPerformanceReportColumn>CampaignId</ns1:KeywordPerformanceReportColumn><ns1:KeywordPerformanceReportColumn>Keyword</ns1:KeywordPerformanceReportColumn><ns1:KeywordPerformanceReportColumn>KeywordId</ns1:KeywordPerformanceReportColumn><ns1:KeywordPerformanceReportColumn>DeviceType</ns1:KeywordPerformanceReportColumn><ns1:KeywordPerformanceReportColumn>BidMatchType</ns1:KeywordPerformanceReportColumn><ns1:KeywordPerformanceReportColumn>Clicks</ns1:KeywordPerformanceReportColumn><ns1:KeywordPerformanceReportColumn>Impressions</ns1:KeywordPerformanceReportColumn><ns1:KeywordPerformanceReportColumn>Ctr</ns1:KeywordPerformanceReportColumn><ns1:KeywordPerformanceReportColumn>AverageCpc</ns1:KeywordPerformanceReportColumn><ns1:KeywordPerformanceReportColumn>Spend</ns1:KeywordPerformanceReportColumn><ns1:KeywordPerformanceReportColumn>QualityScore</ns1:KeywordPerformanceReportColumn></ns1:Columns><ns1:MaxRows>10</ns1:MaxRows><ns1:Scope><ns1:AccountIds><ns2:long>XXXXXXXX</ns2:long></ns1:AccountIds></ns1:Scope><ns1:Sort><ns1:KeywordPerformanceReportSort><ns1:SortColumn>Clicks</ns1:SortColumn><ns1:SortOrder>Ascending</ns1:SortOrder></ns1:KeywordPerformanceReportSort></ns1:Sort><ns1:Time><ns1:PredefinedTime>Yesterday</ns1:PredefinedTime></ns1:Time></ns1:ReportRequest></ns1:SubmitGenerateReportRequest></ns0:Body></SOAP-ENV:Envelope>'
DEBUG:suds.transport.http:received:
CODE: HTTPStatus.OK
HEADERS: Content-Type: text/xml; charset=utf-8
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
Date: Tue, 16 Jan 2018 17:05:51 GMT
Connection: close
Content-Length: 399


MESSAGE:
b'<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:TrackingId xmlns:h="https://bingads.microsoft.com/Reporting/v11">410bb168-7008-447e-8fe7-972fb457b833</h:TrackingId></s:Header><s:Body><SubmitGenerateReportResponse xmlns="https://bingads.microsoft.com/Reporting/v11"><ReportRequestId>30000001231499722</ReportRequestId></SubmitGenerateReportResponse></s:Body></s:Envelope>'
DEBUG:suds.client:HTTP succeeded:
b'<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:TrackingId xmlns:h="https://bingads.microsoft.com/Reporting/v11">410bb168-7008-447e-8fe7-972fb457b833</h:TrackingId></s:Header><s:Body><SubmitGenerateReportResponse xmlns="https://bingads.microsoft.com/Reporting/v11"><ReportRequestId>30000001231499722</ReportRequestId></SubmitGenerateReportResponse></s:Body></s:Envelope>'
Awaiting Download Results . . .
DEBUG:suds.client:sending to (https://reporting.api.bingads.microsoft.com/Api/Advertiser/Reporting/V11/ReportingService.svc)
message:
<suds.sax.document.Document object at 0x000000000EC0DC18>
DEBUG:suds.client:headers = {'Content-Type': 'text/xml; charset=utf-8', 'SOAPAction': b'"PollGenerateReport"', 'User-Agent': 'BingAdsSDKPython 11.5.7 (3, 6, 3)'}
DEBUG:suds.transport.http:sending:
URL: https://reporting.api.bingads.microsoft.com/Api/Advertiser/Reporting/V11/ReportingService.svc
HEADERS: {'Content-Type': 'text/xml; charset=utf-8', 'SOAPAction': b'"PollGenerateReport"', 'User-Agent': 'BingAdsSDKPython 11.5.7 (3, 6, 3)', 'Content-type': 'text/xml; charset=utf-8', 'Soapaction': b'"PollGenerateReport"', 'User-agent': 'BingAdsSDKPython 11.5.7 (3, 6, 3)'}
MESSAGE:
b'<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="https://bingads.microsoft.com/Reporting/v11" xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://bingads.microsoft.com/Reporting/v11"><SOAP-ENV:Header><tns:AuthenticationToken>EwAIA3hlBAAUgdQjroa0siFqrG5FNB4+4uqtlVkAASzJRNx5u6n2+RqcMFVDyoqWs8MceqCtfkS3vabMx+TAOTu0aoG71hGkdcMWcGw/jImoUjxNe6iLI/HqL+Iflo5RhnMZtB1b/drmOw6RCotV8Qv7QfpfZohnPg4X5soCZVwGncPdeKBdDwrpJ8RATd1xdY4aj/Kt+tPjJFHB/NJ+YxCjJrj2XC7rpkGrpyvTyeHRYsxFjrpxfIxaoO7y/YrI22DAiFe1n4NeQ+LI5MygU1BDBBr/cdSxINspeELR6MXbD8HGkllOXaSackBVIgA2jEGceX8d8yhV3lKkTekNpW7/eQ5ZpHbjvOJxz9cqAOFq8lNj5V17UMLkmnrfe40DZgAACNrifECD0znp2AEltVuI44xFGUMxYPpe75cUYwweDXIpwjaacNY6vVex4mwfW4YCt+wbm5HvJxRgSCfX0mg9uhcinGPdZ39MxNZ2MbvN0aU+3FMdZ++L5XNu613y/IeabUFZDUlgVQN4CDfZzDneqgcpmahZueD0TPJVl+X+2pPzTw6Ua/X5OvlgEyid2UmEbc2HRDDBkRYLtr0RnqSGYTmcJe8nlrUjyus9Cl9LopDgyXDI/Rgw5vcvUUIFJLIWjhYgcCgKsk17y9dcYYegQLlo380LgW/uMiMpVjHACg6SDCANhr35mJy3J8y/vd4xFjqTWx2UQCUe6Ci1RrySEj8filCxtarLVLGfTduRXpSLZjjDFTAigmf0nMmIJFI3TAvl2xSvYoQNL6+ZvTKWAY76FZ6Dz0ijHUXcg+Yl6UN1C6Jp5X5UiZy1ppemyA4kJNFmvxT9R/5fRCht/1turXLKFP9pBNSJ4hr6eTIAYDyoKhsmjHR7kdIOpmJaTn1uaJUtmej30hrj7gJVKKBf8onds06epUS+qRf2zIFC6xpPcavvYENaYYYXBOjaANlSr3LqM78o35RZ+JXY7Dy720hyqZzO9sItNEqCxkECUGcElstuLd1NCCs6QH2+w4Bk8AD+IwI=</tns:AuthenticationToken><tns:CustomerAccountId>XXXXXXX</tns:CustomerAccountId><tns:CustomerId>XXXXXXXX</tns:CustomerId><tns:DeveloperToken>XXXXXXXXXXXXX</tns:DeveloperToken></SOAP-ENV:Header><ns0:Body><ns1:PollGenerateReportRequest><ns1:ReportRequestId>30000001231499722</ns1:ReportRequestId></ns1:PollGenerateReportRequest></ns0:Body></SOAP-ENV:Envelope>'
DEBUG:suds.transport.http:received:
CODE: HTTPStatus.OK
HEADERS: Content-Type: text/xml; charset=utf-8
Server: Microsoft-IIS/8.5
X-Powered-By: ASP.NET
Date: Tue, 16 Jan 2018 17:05:53 GMT
Connection: close
Content-Length: 495


MESSAGE:
b'<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:TrackingId xmlns:h="https://bingads.microsoft.com/Reporting/v11">8710a3bd-71cf-437a-b198-ca14846431d5</h:TrackingId></s:Header><s:Body><PollGenerateReportResponse xmlns="https://bingads.microsoft.com/Reporting/v11"><ReportRequestStatus xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><ReportDownloadUrl i:nil="true"/><Status>Success</Status></ReportRequestStatus></PollGenerateReportResponse></s:Body></s:Envelope>'
DEBUG:suds.client:HTTP succeeded:
b'<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:TrackingId xmlns:h="https://bingads.microsoft.com/Reporting/v11">8710a3bd-71cf-437a-b198-ca14846431d5</h:TrackingId></s:Header><s:Body><PollGenerateReportResponse xmlns="https://bingads.microsoft.com/Reporting/v11"><ReportRequestStatus xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><ReportDownloadUrl i:nil="true"/><Status>Success</Status></ReportRequestStatus></PollGenerateReportResponse></s:Body></s:Envelope>'
Download result file: None
Status: Success

Program execution completed`

**Comment by eric-urban** [comment]
@CurtisGreenland we tracked down your request and found that one account has data for the date requested, whereas the other account does not. (Don't worry I will not share the account details in this public forum.) Keep in mind the sample is _just_ a sample and [picks one account](https://github.com/BingAds/BingAds-Python-SDK/blob/master/examples/BingAdsPythonConsoleExamples/BingAdsPythonConsoleExamples/v11/auth_helper.py#L64) to run against. Please double check that you are using the ID for the active account and you should get data returned.

**Comment by CurtisGreenland** [comment]
@eric-urban Thank you.  With a little extra work, I have re-coded so that I can pull all accounts at the same time. And, indeed I have resolved. I appreciate your help.

**Comment by gregroberts** [comment]
I know this has been closed, but I'd just like to say how weird this behaviour is.

I just spent 25 minutes trying to debug why a ReportingDownloadOperation was saying it was '
successful, then the download not actually producing anything.

Looks like the only way to actually determine this has happened at run time is that `download_result_file` returns None.

**Comment by eric-urban** [comment]
@gregroberts thanks for the feedback! To help explain the reason for this change, previously clients had to download and parse the file only to discover in some cases there wasn't any data for the requested time period, scope, etc. Now the service returns nil [ReportDownloadUrl](https://docs.microsoft.com/en-us/bingads/reporting-service/reportrequeststatus#reportdownloadurl) to avoid the unnecessary download/parse steps.

**Comment by amitlimbaskar** [comment]
I have the same issue. When I hard code the account ID s for authorization_data.account _id field and comment following code :  user=get_user_response=customer_service.GetUser(
       UserId=None
    ).User
    accounts=search_accounts_by_user_id(customer_service, user.Id)  

then I get the result when I use first account account from sample code I get result as none. How to get auth_helper to identify all the active accounts and run the report for all of them ?

**Comment by Shellbye** [comment]
> If there is no data for the time period specified in the request, then by design the service return success without any download URL

This is really not a good design.
