### ISSUE TITLE
Frustration after frustation

### ISSUE THREAD

**Issue by AnharMiah** [BingAds/BingAds-Python-SDK#79]
## Sorry this is going to be a long rant. :angry: 

Microsoft **really** needs to take a deep look at themselves:

What was supposed to be a very simple requirement:

* Automate a Keyword report via API

"Sure, no problem Bing Ads seems to have an api" ~ famous last words.. ¯\\_(ツ)\_/¯

![image](https://user-images.githubusercontent.com/11503147/38434330-dae3daaa-39c5-11e8-9c48-66ebe06ae78a.png)

And so became week plus of torture. Now to be fair Google Adwords is worse, but thats fine they have probably 90% market share so they can "afford" to be smug.

Ultimately an `api` is just a FFI (_Foreign Function Interface_) and as such all that it should boil down to is:

* A simple list of remote functions
* A list of parameters types to those said functions
* A description of the return payload type
* Some simple authenticate mechanism.

But of course big enterprises software has to be 3,000 tons of fresh manure because naturally enterprise software has to always be made as **complex** and ridiculous as humanly possible: how else are we to justify all those man hours?

The documentation is a horrendous labyrinth of indirection, coupled with a stupid process equals many hours of pointless waste.

The "Chat Support" those poor souls have to take the brunt of abuse from hoards of frustrated developers but bless them they do try their best!

### The "Support Team" phone calls was a pure nugget of comic genius:

I phoned in, clearly this was a VOIP line that must have been routed via a 24k MODEM that or someone in communications should be fired for using G711 with 500+ms latency. The IVR was just terrible, in the first round I managed to get through to an actual human only to have my line dropped. The next **10** attempts all failed as the IVR simply could not pickup the numbers that I pressed, which doesn't surprise me, they probably didn't follow proper RFC-4733 and the DTMF tones are probably being passed in band :|

Frustrated I turned back to chat, who after a lengthly conversation said that I needed to pass them detailed information which they will then pass onto the "engineers", great something that could probably be solved just by speaking directly to a tech bod now has to have this stupid three way communication ping pong :(

![image](https://user-images.githubusercontent.com/11503147/38434454-46842314-39c6-11e8-8819-12a8a2146651.png)

### Frustration after frustration

OK so after a week plus, what have I managed to do?

- [x] Setup myriad of accounts, apps and other pointless registrations
- [x] Get a "multi-user" token, because `[insert retarded reason]`
- [x] Use massively bloated over engineered OAuth 2.0 "flow" garbage (tm) mechanism
- [x] Actually get the samples to run :|
- [x] Survive not killing support with a frozen cucumber
- [ ] Actually download Keyword report :`(

You know both documentation and `api` do **not** _have_ to be burning mountains of feces. We could have a world where `api`'s are simple, functional and beautiful:

#### _"you may say I'm a dreamer, but I'm not the only one"_

**Comment by AnharMiah** [comment]
@jonmhong tell me about! a simple REST with JSON with tokens in the header, thats all it needs to be really!

I've submitted the SOAP logs over to the support team, just waiting to see what they come back with.

Thanks for the forum pointer, I might try that if things get worse :+1:

**Comment by eric-urban** [comment]
@AnharMiah thanks for reaching out, and I also suggest that you start a thread in the [Bing Ads API Development Forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=BingAds). Currently what scenario can we help unblock? 

@jonmhong yes we heard similar feedback related to parsing the report file. In version 12 the column names are [updated](https://docs.microsoft.com/en-us/bingads/guides/migration-guide?view=bingads-12#reporting-downloadedcolumns) to match the API definition. For example if you request "DeviceType" the downloaded column name will always be "DeviceType" (not "Device type" or another variation). Please feel free to submit additional feature requests [here](https://bingads.uservoice.com/forums/82363-bing-ads-feature-suggestions).
