### ISSUE TITLE
pro-grammatically could n't retrieve keyword suggestions from keyword planner tool  

### ISSUE THREAD

**Issue by BhavanaP** [BingAds/BingAds-Python-SDK#81]
Hi , 

I am new to Bing ads API . i couldn't retrieve the keyword suggestions from bing keyword planner tool. here is the sample program i am following https://docs.microsoft.com/en-us/bingads/guides/code-example-keywords-ads?view=bingads-11. 

i generated the refresh token and followed the above link.I made changes in the program to make use of 'querySearchParameter' but the result set is showing each keywordIdea with following values . AdGroupId,AdGroupName,AdImpressionShare,Competition,Keyword,MonthlySearchCounts,Relevance,Source,SuggestedBid.

i am looking to get the keyword suggestions from keyword planner. Please Suggest

thank you ,
Bhavana

**Comment by eric-urban** [comment]
@BhavanaP the link you provided was for keywords and ads campaign management. The keyword_planner.py sample ([here](https://docs.microsoft.com/en-us/bingads/guides/code-example-keyword-planner?view=bingads-12) and [here](https://docs.microsoft.com/en-us/bingads/guides/code-example-keyword-planner?view=bingads-12)) can be used to get suggested keywords. If you are also looking for traffic estimates for the returned Keyword ideas, then you can extend the sample by calling [GetKeywordTrafficEstimates](https://docs.microsoft.com/en-us/bingads/ad-insight-service/getkeywordtrafficestimates?view=bingads-12). I hope this helps!

**Comment by BhavanaP** [comment]
@eric-urban Thanks a lot .
