### ISSUE TITLE
Report Columns are Misaligned

### ISSUE THREAD

**Issue by jonmhong** [BingAds/BingAds-Python-SDK#82]
In the request, I have to specify a column called `TimePeriod` then the report returns a column called `GregorianDate`.

Same thing with countryorregion

**Comment by eric-urban** [comment]
@jonmhong this has been resolved with [version 12](https://docs.microsoft.com/en-us/bingads/guides/migration-guide?view=bingads-12#reporting-downloadedcolumns). Please reach out if you observe any discrepancies in version 12.
