### ISSUE TITLE
BulkAdGroupLocationCriterion Target mapping breaks in Python 3

### ISSUE THREAD

**Issue by mikeengland** [BingAds/BingAds-Python-SDK#84]
Hi,
In the BulkAdGroupLocationCriterion Target mappings, the code tries to cast the value to a Long data type if the value is defined. This is valid in Python 2, however in Python 3 it no longer exists.

`NameError: name 'long' is not defined`

https://github.com/BingAds/BingAds-Python-SDK/blob/master/bingads/v11/bulk/entities/target_criterions/bulk_ad_group_location_criterion.py#L68

The solution would be to use long if the Python version is 2, and int if it is Python 3.

Thanks!

**Comment by qitia** [comment]
@mikeengland  Thanks for raising this issue. will fix it soon.

**Comment by mikeengland** [comment]
@qitia Sounds good to me! Thank you.

**Comment by qitia** [comment]
oh no need to create PR here. We will release version 11.12.2 at around 18 May. I hope it is not too late for you. Thanks @mikeengland

**Comment by mikeengland** [comment]
@qitia That is fine, thank you! If I need to change it in the meantime, I can always fork the library.

**Comment by mikeengland** [comment]
@qitia It looks like this is fixed now. If it is, please feel free to close this! Thanks!

**Comment by qitia** [comment]
@mikeengland yes new version released and this has been fixed.
