### ISSUE TITLE
How to generate the refresh token after expiration without the need to open a browser

### ISSUE THREAD

**Issue by aj07mm** [BingAds/BingAds-Python-SDK#88]
Couldn't find a method to generate the refresh token after expiration without the need to open a browser and type the credentials then paste it back. Everything happens on this line: `webbrowser.open(auth_data.authentication.get_authorization_endpoint(), new=1)`

Is there a way?

**Comment by eric-urban** [comment]
@aj07mm you can call request_oauth_tokens_by_refresh_token as shown in [this example](https://github.com/BingAds/BingAds-Python-SDK/blob/20d87e2b6455e293c2013cfd48b7054a5f92ad07/examples/BingAdsPythonConsoleExamples/BingAdsPythonConsoleExamples/v12/auth_helper.py#L82).

I hope this helps!
