### ISSUE TITLE
Question: how can I cache an access_token?

### ISSUE THREAD

**Issue by iamdoron** [BingAds/BingAds-Python-SDK#9]
Hi,

I'm using the api in a command line script - but every time I run it it refreshes the refresh token and gets a new access token (I'm using the example code) - I don't see a reason for it, since I already have an access token that can hold (for example) for an hour after I run it once. Is there a way to create authentication and initialize it with an access_token and refresh_token (to be used when the access_token has expired)?

For example, I can manage to do this via undocumented property: 

```python
    authentication = OAuthDesktopMobileAuthCodeGrant(
        client_id = CLIENT_ID
    )
    refresh_token = get_refresh_token()
    access_token = get_access_token()

    authentication._oauth_tokens = OAuthTokens(access_token, int(3600), refresh_token);
```

It works pretty well, and all the services refresh the token if necessary. 
The access token has to be saved at the refresh callback, similar to the example code.

**Comment by imfu** [comment]
Hi, oauth_token is accepted in OAuthAuthorization constructors since 10.4.4. you can build your own OAuthTokens based on your cached access_token and init the OAuthAuthoriztion entities. 

Thanks.
