### ISSUE TITLE
Example Django project is broken

### ISSUE THREAD

**Issue by jamesgecko** [BingAds/BingAds-Python-SDK#91]
The [requirements.txt](https://github.com/BingAds/BingAds-Python-SDK/blob/master/examples/djangowebapp/requirements.txt) specifies `django<2`. This installs the latest non-2.0 version of Django; presently 1.11.4.

[`DjangoWebProject/urls.py`](https://github.com/BingAds/BingAds-Python-SDK/blob/master/examples/djangowebapp/DjangoWebProject/urls.py#L16) uses the `patterns` method, which is raises an error in Django 11; [the way URLs are specified has changed](https://docs.djangoproject.com/en/1.11/topics/http/urls/). It hasn't been valid code since Django 1.8 was released, which means this has been broken for three years somehow.

Either the application should be upgraded, or the Django version should be locked to 1.7.

**Comment by SStembridge** [comment]
As a note, Django 1.7 utilises HTMLParseError which is deprecated in Python 3.3 and removed in Python 3.5, so trying to run this example with up to date Python becomes impossible.

**Comment by eric-urban** [comment]
@SStembridge thank you

**Comment by eric-urban** [comment]
@jamesgecko @SStembridge we've moved the web example to a walk-through i.e., [here](https://docs.microsoft.com/en-us/bingads/guides/walkthrough-web-application-python). Thanks

**Comment by jamesgecko** [comment]
Thanks! I appreciate it. :-)
