### ISSUE TITLE
Issue after Upgrade to v11.12.4 

### ISSUE THREAD

**Issue by nmylarappa** [BingAds/BingAds-Python-SDK#95]
Hi,

We are seeing this below issue after we upgraded the SDK to 11.12.14.

   from bingads.v11.bulk import *
 File "/usr/local/lib/python2.7/dist-packages/bingads/v11/bulk/__init__.py", line 11, in <module>
   from .file_reader import *
 File "/usr/local/lib/python2.7/dist-packages/bingads/v11/bulk/file_reader.py", line 2, in <module>
   from .entities.bulk_entity import BulkEntity
 File "/usr/local/lib/python2.7/dist-packages/bingads/v11/bulk/entities/__init__.py", line 4, in <module>
   from .common import *
 File "/usr/local/lib/python2.7/dist-packages/bingads/v11/bulk/entities/common.py", line 1, in <module>
   from bingads.v11.internal.bulk.string_table import _StringTable
 File "/usr/local/lib/python2.7/dist-packages/bingads/v11/internal/__init__.py", line 4, in <module>
   from .extensions import *
 File "/usr/local/lib/python2.7/dist-packages/bingads/v11/internal/extensions.py", line 42, in <module>
   TargetSetting_Type = type(_CAMPAIGN_OBJECT_FACTORY_V11.create('TargetSetting'))
 File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 218, in create
   raise TypeNotFound(name)
suds.TypeNotFound: Type not found: 'TargetSetting''''

**Comment by qitia** [comment]
I did not reproduce this issue. Could you please confirm there is nothing env change but just upgrade this SDK to 11.12.4? does it work with 11.12.3?

**Comment by nmylarappa** [comment]
Hello,

I am seeing the below issue after pointing it to api version 12.





DEBUG:suds.client:sending to (https://reporting.api.bingads.microsoft.com/Api/Advertiser/Reporting/V12/ReportingService.svc)
message:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:tns="https://bingads.microsoft.com/Reporting/v12" xmlns:ns0="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns2="https://bingads.microsoft.com/Reporting/v12" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header>
      <tns:AuthenticationToken>EwAQA3hlBAAUS26g+KHGWHId2M6BBkwqoP+OSdAAAclgNdm3ieOlroYKeeWN80oMqzrLuMcibsz4dnVzKcViTd8S0kdIM8AJ2yEf3RNkSao/je1JDQph+Bc6Hpsxaqn3V61vdzfidBjDq85GW1quJtf8Um1V/IJYoJt7uAXgC2+7gqXRdS+glogwFEaVCrAcX0u7TkBNOST0m423579NEI2icUMd0TH4n0Na3ObCYF7iKN7JiLCOVZmLsskATeBJ/gYdc4727RwZkJZxjC4wdNv4nCDBhM9DZv2czy6pjBT8D9PYGuwoh8HW4ywDBkyBXtyjLRsIrHXfuX0gv5IGgmmezyAYu+neOa3C4eQUVWUfAFKql1FTY4hWFBktskQDZgAACFV8Kz22Hz8X4AHYvK1VqcP0WggJrsUTvijlab5g0Tokogg14uRA1vgkqfUuMH/KWigYxA1qEF43Yim5k3PtqnI8pSjfuK0SOsiAD0TdFijBwSwM2BzAEFSUPhI9ryhVC7iRghm0rkvbwNOnwKLuyx7grnNPrcw6WNl4CtcpuJTHxHyFNCxTYErPTUgo0AQXLEaITDBCnz+XKKFVsjC9klkOANZ4hWUNqVWGR4uIxmMXn4EnsvPJAuvR05/yp8dHlSl4swJum0GqXXSdDbiyT9B+02f/fAxapJtpK2u6zyuI3IMdRrUp/J4T06ipxqfbEbCQzvyVbQDK/BWzs4NLrcRVgn53FtONMzcMFpKrR6l74dFsYe+P3sK1XbpShPpHJDXjgSk9nJm3jqQJMqIiSjLboNVemL5WfIX1pqwfYlRuVxqB8FgpO9XoQKJBcmoDzQN9nhGXE8c+gh/W1dZaJcYqW/1MpWqAFpA9gbFKixfzovzoMX9rfr0aAgNmCSR515Uo9ss1osdsV0xdZNsMoMsB7jaXF0C8Vipk73iwm0GXx1CbcZXbLIPpgQWx39XNn+7B+mS/dQ+VnFAlzLFb+UCftBJyXDWuoh8umi9j9yCsyoUkIqUMCkTWqS03I+IhPuv86Z9BhdLTVpohAg==</tns:AuthenticationToken>
      <tns:CustomerAccountId>47091023</tns:CustomerAccountId>
      <tns:CustomerId>18181048</tns:CustomerId>
      <tns:DeveloperToken>115I3QYKX8699642</tns:DeveloperToken>
   </SOAP-ENV:Header>
   <ns1:Body>
      <ns2:SubmitGenerateReportRequest>
         <ns2:ReportRequest xsi:type="ns2:KeywordPerformanceReportRequest">
            <ns2:Format>Csv</ns2:Format>
            <ns2:Language>English</ns2:Language>
            <ns2:ReturnOnlyCompleteData>false</ns2:ReturnOnlyCompleteData>
            <ns2:Aggregation>Daily</ns2:Aggregation>
            <ns2:Columns>
               <ns2:KeywordPerformanceReportColumn>AccountNumber</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>AccountName</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>AccountId</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>CurrencyCode</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>CampaignId</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>CampaignName</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>CampaignStatus</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>KeywordId</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>Keyword</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>KeywordStatus</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>TimePeriod</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>DeviceType</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>BidMatchType</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>AveragePosition</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>Spend</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>Clicks</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>Conversions</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>Impressions</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>AdGroupId</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>AdGroupName</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>AdGroupStatus</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>AdDistribution</ns2:KeywordPerformanceReportColumn>
               <ns2:KeywordPerformanceReportColumn>Network</ns2:KeywordPerformanceReportColumn>
            </ns2:Columns>
            <ns2:Scope>
               <ns2:AccountIds>
                  <ns0:long>47091023</ns0:long>
               </ns2:AccountIds>
            </ns2:Scope>
            <ns2:Time>
               <ns2:CustomDateRangeEnd>
                  <ns2:Day>11</ns2:Day>
                  <ns2:Month>09</ns2:Month>
                  <ns2:Year>2018</ns2:Year>
               </ns2:CustomDateRangeEnd>
               <ns2:CustomDateRangeStart>
                  <ns2:Day>06</ns2:Day>
                  <ns2:Month>09</ns2:Month>
                  <ns2:Year>2018</ns2:Year>
               </ns2:CustomDateRangeStart>
               <ns2:ReportTimeZone/>
            </ns2:Time>
         </ns2:ReportRequest>
      </ns2:SubmitGenerateReportRequest>
   </ns1:Body>
</SOAP-ENV:Envelope>
DEBUG:suds.client:headers = {'SOAPAction': '"SubmitGenerateReport"', 'Content-Type': 'text/xml; charset=utf-8', 'User-Agent': 'BingAdsSDKPython 11.12.4 (2, 7, 6)'}
DEBUG:suds.client:HTTP failed - 500 - Internal Server Error:
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode xmlns:a="http://schemas.microsoft.com/net/2005/12/windowscommunicationfoundation/dispatcher">a:DeserializationFailed</faultcode><faultstring xml:lang="en-US">The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter https://bingads.microsoft.com/Reporting/v12:ReportRequest. The InnerException message was 'Invalid enum value '' cannot be deserialized into type 'Microsoft.AdCenter.Advertiser.Reporting.Api.DataContracts.Enum.ReportTimeZone'. Ensure that the necessary enum values are present and are marked with EnumMemberAttribute attribute if the type has DataContractAttribute attribute.'.  Please see InnerException for more details.</faultstring></s:Fault></s:Body></s:Envelope>
ERROR:suds.client:<suds.sax.document.Document instance at 0x7fbaa0cf7e18>
Traceback (most recent call last):
  File "/home/nmylarappa/dwh/Scripts/mktg_bing_keyword_perf_f/pythonscripts/bing_download.py", line 442, in <module>
    output_webfault_errors(ex)
  File "/home/nmylarappa/dwh/Scripts/mktg_bing_keyword_perf_f/pythonscripts/bing_download.py", line 216, in output_webfault_errors
    raise Exception('Unknown WebFault')
Exception: Unknown WebFault

**Comment by qitia** [comment]
hello @nmylarappa seems you are reporting two different issues? May I know if you still repro the 'TargetSetting' issue with V11?

For the second Download Reporting issue. Though it is 'nillabe', missing of request.Time**.ReportTimeZone** will cause this issue. Currently you have two ways to work around this:
1, set a valid timezone for this parameter - FYI the valid timezone is listed [here](https://docs.microsoft.com/en-us/bingads/guides/time-zones?view=bingads-12), or 
2, if you do not know which should be used, try add this before submitting the request
        submit_request = self.reporting_service.factory.create('KeywordPerformanceReportRequest')
        **delattr(submit_request.Time, "ReportTimeZone")**
        ...

**Comment by harry1180** [comment]
Thanks @qitia a lot this solved our issue. but we have this same issue for campaign performance end point too. we deleted ReportTimeZone attribute. Do we have to delete any other attributes ?
are we missing something else ?

**Comment by harry1180** [comment]
Yes I have (I am from Naveen's team btw)

**Comment by harry1180** [comment]
I tried all columns with None value. "delattr(report_request.Time, "ReportTimeZone")
    delattr(report_request.Time, "PredefinedTime")
    delattr(report_request.Filter, "AccountStatus")
    delattr(report_request.Filter, "AdDistribution")
    delattr(report_request.Filter, "DeviceOS")
    delattr(report_request.Filter, "DeviceType")
    delattr(report_request.Filter, "Status")
    delattr(report_request.Scope, "AdGroups")
    delattr(report_request.Scope, "Campaigns")
but still it did not work

**Comment by harry1180** [comment]
may be this long can help u understand issue more in detail
=== Start downloading CampaignPerformanceReport_B017WYJL.csv ===
DEBUG:suds.client:sending to (https://reporting.api.bingads.microsoft.com/Api/Advertiser/Reporting/V12/ReportingService.svc)
message:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:tns="https://bingads.microsoft.com/Reporting/v12" xmlns:ns0="http://schemas.microsoft.com/2003/10/Serialization/Arrays" xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns2="https://bingads.microsoft.com/Reporting/v12" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header>
      <tns:AuthenticationToken>XXXXX</tns:AuthenticationToken>
      <tns:CustomerAccountId>XXXXXXXX</tns:CustomerAccountId>
      <tns:CustomerId>XXXXX</tns:CustomerId>
      <tns:DeveloperToken>XXXXX</tns:DeveloperToken>
   </SOAP-ENV:Header>
   <ns1:Body>
      <ns2:SubmitGenerateReportRequest>
         <ns2:ReportRequest xsi:type="ns2:CampaignPerformanceReportRequest">
            <ns2:Format>Csv</ns2:Format>
            <ns2:Language>English</ns2:Language>
            <ns2:ReturnOnlyCompleteData>false</ns2:ReturnOnlyCompleteData>
            <ns2:Aggregation>Daily</ns2:Aggregation>
            <ns2:Columns>
               <ns2:CampaignPerformanceReportColumn>AccountId</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>AccountName</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>AccountNumber</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>CampaignId</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>CampaignName</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>Status</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>TimePeriod</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>DeviceType</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>CurrencyCode</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>Spend</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>Impressions</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>Clicks</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>AverageCpc</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>AverageCpp</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>AveragePosition</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>Ctr</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>Conversions</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>Network</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>AdDistribution</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>QualityScore</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>Revenue</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>RevenuePerAssist</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>ReturnOnAdSpend</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>RevenuePerConversion</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>CostPerAssist</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>CostPerConversion</ns2:CampaignPerformanceReportColumn>
               <ns2:CampaignPerformanceReportColumn>ConversionRate</ns2:CampaignPerformanceReportColumn>
            </ns2:Columns>
            <ns2:Scope>
               <ns2:AccountIds>
                  <ns0:long>XXXXXXXX</ns0:long>
               </ns2:AccountIds>
            </ns2:Scope>
            <ns2:Time/>
         </ns2:ReportRequest>
      </ns2:SubmitGenerateReportRequest>
   </ns1:Body>
</SOAP-ENV:Envelope>
DEBUG:suds.client:headers = {'SOAPAction': '"SubmitGenerateReport"', 'Content-Type': 'text/xml; charset=utf-8', 'User-Agent': 'BingAdsSDKPython 11.12.4 (2, 7, 6)'}
DEBUG:suds.client:HTTP failed - 500 - Internal Server Error:
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode xmlns:a="http://schemas.microsoft.com/net/2005/12/windowscommunicationfoundation/dispatcher">a:DeserializationFailed</faultcode><faultstring xml:lang="en-US">The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter https://bingads.microsoft.com/Reporting/v12:ReportRequest. The InnerException message was 'Invalid enum value 'Status' cannot be deserialized into type 'Microsoft.AdCenter.Advertiser.Reporting.Api.DataContracts.Enum.CampaignPerformanceReportColumn'. Ensure that the necessary enum values are present and are marked with EnumMemberAttribute attribute if the type has DataContractAttribute attribute.'.  Please see InnerException for more details.</faultstring></s:Fault></s:Body></s:Envelope>
ERROR:suds.client:<suds.sax.document.Document instance at 0x7f5a9868d5f0>
Traceback (most recent call last):
  File "/home/hkoppuravuri/dwh/Scripts/mktg_bing_campaign_perf_f/pythonscripts/bing_download.py", line 448, in <module>
    output_webfault_errors(ex)
  File "/home/hkoppuravuri/dwh/Scripts/mktg_bing_campaign_perf_f/pythonscripts/bing_download.py", line 216, in output_webfault_errors
    raise Exception('Unknown WebFault')
Exception: Unknown WebFault

**Comment by qitia** [comment]
@nmylarappa @harry1180 Are you switching from V11 to V12? Please notice that there are some breaking changes when we upgrade to v12. For example the column names for CampaignPerformanceReport are not exactly same. Please see [v11](https://reporting.api.sandbox.bingads.microsoft.com/Api/Advertiser/Reporting/V11/ReportingService.svc?singleWsdl) and [v12](https://reporting.api.sandbox.bingads.microsoft.com/Api/Advertiser/Reporting/V12/ReportingService.svc?singleWsdl) for reference. I think for v12, it should be CampaignStatus what you want.

**Comment by qitia** [comment]
@nmylarappa  @harry1180  I suppose your issue has been resolved. I close this issue and you can re-open it in case more concern.

**Comment by harry1180** [comment]
Hi @qitia ,

Thanks for helping us in our earlier issue. We are in need of some info so thought of posting it in here.

we are facing an issue with the reporting data related to four campaigns in particular for our camapign section end point.
There is this column called Addistribution which should have 'Search' or 'Content' or 'Native' but we are getting a new value named 'Audience'. This cannot be an appropriate value for ad distribution as far as we understand.
We have this value only for the recent records and that too after version upgrade.
Can you confirm on this once pls?

we are noticing this value for four of our campaigns. Happy to have a session to discuss on this. 
If it is a valid value we need to change our ETL logic to facilitate the same. Kindly confirm on the same.
