### ISSUE TITLE
Bing version 12

### ISSUE THREAD

**Issue by nmylarappa** [BingAds/BingAds-Python-SDK#96]
We have installed this version of Bing python SDK  and running our jobs. bingads==11.12.4. 

How do I make sure I am not making calls to  API v.11 and only to v.12?

**Comment by qitia** [comment]
in class ServiceClient, we have a parameter 'version', make sure you pass 12 or 'v12', you will make call to API v12. See example: https://github.com/BingAds/BingAds-Python-SDK/blob/07a309a47e5e44fce9ac2dad26cff481a045cfc5/examples/BingAdsPythonConsoleExamples/BingAdsPythonConsoleExamples/v12/ad_extensions.py#L392
